nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/utils/reroute.py
src/griptape_nodes/exe_types/connections.py
src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- migrating PR from EE. 
- The re-router object should take the input and re-route out to the outputs.
- [old PR ](https://github.com/griptape-ai/griptape-vsl-execution-engine/pull/239)

Rerouter Node Logic

---

src/griptape_nodes/node_library/script_registry.py
src/griptape_nodes/retained_mode/events/script_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/settings.py

We need provenance for which a script was created. This includes the engine version (in case a breaking change comes in that we cannot overcome) and which libraries were used to build the scene. We add this additional data now alongside the existing script metadata.
Closes #13

adding engine ver and libraries to script info for dependency management

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/log_manager.py
src/griptape_nodes/retained_mode/retained_mode.py

Added LogManager to the singleton GriptapeNodes. This gives us an opportunity to do GUI-specific hooks for choosing which log items we wish to emit to the editor.
Problems:
1. I can't bring it down into the immediate mode (exe_types/, etc.) dirs without hauling in the entirety of Griptape Nodes
2. Some of the standalone managers, such as ConfigManager, also can't bring it in without circular dependencies.
I've left those alone while hitting the major locs.

Add Log Manager

---

CONTRIBUTING.md

By default, the engine looks for the nodes library in the location we install to:
https://github.com/griptape-ai/griptape-nodes/blob/24d1fdab898e1617793eeb55b7a5a87c161502ef/install.sh?plain=1#L63-L64
https://github.com/griptape-ai/griptape-nodes/blob/24d1fdab898e1617793eeb55b7a5a87c161502ef/src/griptape_nodes/retained_mode/managers/settings.py?plain=1#L52-L54
For developers developing nodes locally, they need to update this path to the local repo.

docs: update contributing guide on using local nodes library

---

src/griptape_nodes/exe_types/connections.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- We had some old code that dated back to when we were representing connections differently. I removed that code, and refactored a bug that I then caught in connections where deleting a connection was deleting all connections from that parameter, not just the one connection that needed to be deleted. (This wasn't an issue with the old hack, but needed to be modified on removal of that).

Removed Temporary Hack for Connection Deletion

---

src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Closes #25 and #15 . 
- Updated node creation to check types to catch errors before `GetAllNodeInfoRequest`. 
- Updated `GetParameterValueRequest` with a try-catch. All exceptions raised should be logged, and not shut down the engine. 
- Noticed that `get_flow_by_name` threw a `KeyError` instead of returning `None`, so I updated code to make sure to account for that.
- Try-catches the json.loads for libraries so it just doesn't load that library instead of shutting down engine

Prevents Engine shutdown on library or node error

---

nodes/griptape_nodes_library.json
src/griptape_nodes/node_library/script_registry.py
src/griptape_nodes/retained_mode/events/script_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/settings.py

Scene saving now records the version of a library (now a field in the library metadata) so that we can catch regressions, attempt migrations, or at least alert users if a change has occurred. Doing this as preparation for the example node library template repo.

Include library version when saving scene so that we can catch it later if there is an update needed.

---

src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_fake_socket.py

`GRIPTAPE_NODES_API_BASE_URL` can be set in the `.env` for local development

Update nodes API URL to pull from environment

---

nodes/griptape_nodes_library/start_flow.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/events/validation_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- Received a request from @aodhanroche to package validation into `StartFlowRequest` and `ResolveNodeRequest`. 
- Validation is now called by both of these requests, and if validation fails, the exceptions are returned. 
```
class StartFlowResult_Failure(ResultPayload_Failure):
validation_exceptions: list[Exception] | None = None
class ResolveNodeResult_Failure(ResultPayload_Failure):
validation_exceptions: list[Exception] | None = None
```
Now the list of exceptions is returned in the event on a failure (If validation is WHY it failed). 
closes #55

Add Validation to Start Flow and Resolve Node on request

---

install.ps1
install.sh

- Fix install script config format
- Remove confirmation of overwriting config file. It doesn't work with bash piping and isn't a big deal if they overwrite.

fix: solve install script issues

---

src/griptape_nodes/retained_mode/griptape_nodes.py

- library was getting overwritten by Changing node metadata when the node was getting moved around on the screen. slightly modified how we save metadata to prevent stuff like this from happening (the user can now only partially modify metadata instead of having to save and use it all)

Preventing important Node Metadata from getting overwritten

---

README.md
nodes/griptape_nodes_library/end_flow.py
nodes/griptape_nodes_library/start_flow.py
pyproject.toml
src/griptape_nodes/api/app.py
src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/events/app_events.py
src/griptape_nodes/retained_mode/events/arbitrary_python_events.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/events/config_events.py
src/griptape_nodes/retained_mode/events/connection_events.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/events/library_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/events/object_events.py
src/griptape_nodes/retained_mode/events/os_events.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/events/script_events.py
src/griptape_nodes/retained_mode/events/validation_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/event_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/retained_mode.py
tests/integration/conftest.py
tests/integration/retained_mode/events/test_node_events.py

Goes against python [naming conventions](https://peps.python.org/pep-0008/#class-names). Tests will fail until https://github.com/griptape-ai/griptape-nodes/pull/112 goes in.

refactor: don't use underscores in class names

---

src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_socket_manager.py
src/griptape_nodes/retained_mode/managers/log_manager.py

also need to selectively remove the event handler for the logger otherwise it recursively fails to send events every time anything is logged.
closes #121

Add retries on websocket connect and failures

---

nodes/griptape_nodes_library.json

Fixes:
```
Attempted to register Node class 'FileManagerToolNode' from Library 'Griptape Nodes Library', but a Node with that name from that Library was already registered. Check to ensure you aren't re-adding the same libraries multiple times.
Attempted to register Node class 'LoadImageNode' from Library 'Griptape Nodes Library', but a Node with that name from that Library was already registered. Check to ensure you aren't re-adding the same libraries multiple times.
Attempted to register Node class 'SimpleAgentNode' from Library 'Griptape Nodes Library', but a Node with that name from that Library was already registered. Check to ensure you aren't re-adding the same libraries multiple times.
```

fix: use correct class names in griptape nodes library

---

CONTRIBUTING.md
README.md

Closes #11 -- an `.example.env` should not be needed with these up to date instructions.

docs: improve contributing guidelines

---

CONTRIBUTING.md
src/griptape_nodes/retained_mode/griptape_nodes.py

Quick one. We were catching the wrong type of error when a node couldn't be found, so it was crashing the machine instead of returning a failure result. 
The other issue: on occasion (not every time! but randomly sometimes) the connection deletion requests get out of order. They are sent in the right order from the GUI, but something happens, maybe on the api layer, where the last DeleteConnection request comes AFTER the DeleteNodeRequest. 
I think that the GUI should just only make 1 call: DeleteNodeRequest, because that handles all connection deletion anyways. Then this won't happen. Thoughts? @aodhanroche @SavagePencil

Fix connection deletion error

---

nodes/griptape_nodes_library/create_image.py
nodes/griptape_nodes_library/drivers/anthropic_prompt_driver.py
nodes/griptape_nodes_library/load_image.py
nodes/griptape_nodes_library/save_text.py
nodes/griptape_nodes_library/utilities.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Per customer feedback, they wanted a shorthand for `GriptapeNodes.get_logger()`. I would have put this up in `node_types.py` but didn't want to deal with importing all of retained mode, so instead I made a helper function up in `GriptapeNodes` (which individual nodes will use) called `logger`.
I updated all instances of `print()` to use `logger()` in the existing node code.

Task/make logger easy when node authoring.

---

src/griptape_nodes/api/app.py

It looked kinda trashy having a bunch of debug spew occur after the "engine started". I am concerned that calling the `process_app_event` directly may have unintended side effects, so someone please vet this doesn't upset it.

Put engine start message to show up AFTER app initialization complete event finishes

---

src/griptape_nodes/__init__.py
src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_socket_manager.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/settings.py

- Add `gtn init` command to prompt the user through setting workspace and api key.
- Run this command if the user doesn't have a `~/.config/griptape_nodes` directory (should only be on install).
- Default `workspace_directory` to `cwd / GriptapeNodes` rather than `home / GriptapeNodes`.

feat: add init workflow

---

src/griptape_nodes/api/app.py
src/griptape_nodes/retained_mode/managers/secrets_manager.py

#206 appears to have been a faulty `.env` file. This PR updates our logging to be more informative about what is happening when there is a faulty `.env`.
Closes #206

refactor: improve/add error messages when getting environment variables

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/app_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- Using lazy import removes the need to send the app event back and forth. 
- Closes #18 .along with #176

Removing app events from resolution

---

src/griptape_nodes/retained_mode/griptape_nodes.py

For now we're just going to let the editor come on in with a new session.

refactor: don't fail on new session

---

pyproject.toml
scripts/coloring_book.py
scripts/prompt_an_image.py
scripts/render_logs.py
src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_socket_manager.py
src/griptape_nodes/exe_types/connections.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/events/generate_request_payload_schemas.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/log_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/managers/secrets_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/retained_mode.py

Adds the ability to change the log level via a new settings field, `log_level`. Also refactors usages of `print` and `LogManager.get_logger` to use native logging mechanism, `logging.getLogger`. This was required to avoid circular dependency issues.
Open questions:
1. [This rule](https://docs.astral.sh/ruff/rules/error-instead-of-exception/) encourages us to use `logger.exception` over `logger.error` inside of exceptions so that the traceback is shown. While I generally agree with this rule, even with [rich_tracebacks](https://rich.readthedocs.io/en/stable/logging.html#handle-exceptions), this can be kind of scary looking to users.
What do we think? Do we want to ignore this rule in all scenarios where we properly handle the exception?
2. Loggers under the `api` package have been …

Use Loggers Over Prints and Add Setting For Log Level

---

nodes/griptape_nodes_library/agents/base_agent.py

I was not getting the Param Groups or their children until I made this change to match the other group testing nodes I had seen previously

Fix param group syntax

---

pyproject.toml
src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/exe_types/data_types.py
src/griptape_nodes/node_library/script_registry.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/events/payload_registry.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/traits/minmax.py
src/griptape_nodes/traits/slider.py
src/griptape_nodes/traits/trait_registry.py

- [N999](https://docs.astral.sh/ruff/rules/invalid-module-name/)
- [RUF012](https://docs.astral.sh/ruff/rules/mutable-class-default/)
@SavagePencil for RUF012, can you please make sure these are actually intended to be `ClassVar`s?

Remove Ruff Rules N999 and RUF012

---

src/griptape_nodes/retained_mode/griptape_nodes.py

The UI now sends over SessionStartRequests more aggressively. This
generates a lot of misleading noise without this.

fix: update session start logs to more accurately reflect actions

---

src/griptape_nodes/api/app.py
src/griptape_nodes/retained_mode/managers/config_manager.py

This happens because we initialize an GriptapeNodes instance for each thread (main thread, background event queue).
Fixes https://github.com/griptape-ai/griptape-nodes/issues/246

fix: log ConfigManager's loaded logs in app, not constructor

---

src/griptape_nodes/app/app.py

This reduces confusion on "which version of the engine am I on?" and assists in debug.

Add engine version to the engine started box

---

CONTRIBUTING.md
README.md
docs/configuration.md
docs/getting_started.md
docs/index.md
docs/nodes/dict/merge_key_value_pair.md
docs/nodes/drivers/griptape_cloud_image_driver.md
docs/nodes/overview.md
docs/nodes/rules/create_ruleset.md
docs/nodes/text/create_multiline_text.md
docs/nodes/tools/tool_list.md
docs/reference/glossary.md
docs/reference/retained_mode.md
pyproject.toml
uv.lock

Copied from griptape repo. `make format` now formats markdown files in a mkdocs compatible format.
----
📚 Documentation preview 📚: https://griptape-nodes--303.org.readthedocs.build//303/

style: add mdformat plugins for mkdocs, format repo

---

nodes/griptape_nodes_library/image/create_image.py

set prompt to multiline
removed output port from enhance_prompt

318-image-generation-prompt-on-create-image-should-be-multiline

---

nodes/griptape_nodes_library/number/create_float.py
nodes/griptape_nodes_library/number/create_int.py
nodes/griptape_nodes_library/number/display_float.py
nodes/griptape_nodes_library/number/display_int.py

fixed errors on create and display float and integer.
* values were being set as strings, so now are set as correct types
* didn't catch for values not being set, now  we are.

316-fix-issue-where-no-default-value-is-set-and-no-value-on-the-node-eg-create-float-had-no-value-set

---

docs/faq.md
docs/getting_started.md

----
📚 Documentation preview 📚: https://griptape-nodes--382.org.readthedocs.build//382/

381 add some "where am i installed?" stuff to faq + unifying some getting started/configuration content re: workspace dir

---

.github/workflows/code-checks.yml
Makefile
docs/faq.md
docs/getting_started.md
docs/how_to/making_custom_nodes.md
docs/how_to/making_custom_scripts.md
docs/nodes/agents/create_agent.md
docs/nodes/agents/run_agent.md

Use `make/check` rather than `ruff format` command in github actions. This was originally done because of `mdformat` trying to format `.venv` in CI but we can work around that.
----
📚 Documentation preview 📚: https://griptape-nodes--393.org.readthedocs.build//393/

Fix CI Formatting

---

nodes/griptape_nodes_library/agents/base_agent.py
nodes/griptape_nodes_library/agents/run_agent.py

The RunAgent node wasn't working with `prompt_context` properly, so I've fixed that, and also the `Agent Configurations` group was visible, but it shouldn't be for this node. That's now been removed.

fixed prompt_context

---

nodes/griptape_nodes_library/agents/base_agent.py
nodes/griptape_nodes_library/agents/create_agent.py
nodes/griptape_nodes_library/agents/run_agent.py
nodes/griptape_nodes_library/image/create_image.py
src/griptape_nodes/app/app.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

These expressions will be run in a background thread. Node processing will resume when they are done.
Before this is merged the UI needs to be fixed to properly track finished node executions.
Closes #361 
Closes #312

feat: add ability for nodes to yield background work

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py

This PR makes the following changes:
- Don't initialize the system config directory unless explicitly running through the `gtn init` flow (either explicitly or implicitly)
- Set the `workspace_directory` to the resolved path rather than a relative one.
- `gtn init` now saves the workspace directory to the system config rather than the current working directory.
- Config Manager now correctly saves the delta of the config file changes rather than the entire config.
- Look in the current workspace directory when searching for config files.
Closes #399

Refactor Config Initalization

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/settings.py

This one was tricky because it's a chicken and egg problem. The `workspace_directory` is set in configuration files, but the `workspace_directory` _informs_ the configuration files. I'm not in love with the solution because it requires loading the settings twice, but it makes some overdue refactors and solves the immediate problem.
Closes #422

fix: consider config files in workspace directory

---

src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/secrets_manager.py

This PR greatly simplifies how config/secrets work. Key changes:
1. Drop support for `yaml`/`toml` files. This only adds complexity right now.
2. Setting config through the UI will _always_ set the values in the user config file (`~/.config/griptape_nodes/griptape_nodes_config.json`).
3. Getting config will merge configs from exactly **two** places: the user config file (`~/.config/griptape_nodes/griptape_nodes_config.json`) and, optionally, a workspace config file (`{workspace_dir}/griptape_nodes_config.json`).
4. Setting secrets through the UI will _always_ set the values in the user secrets file (`~/.config/griptape_nodes/.env`).
5. Getting secrets will merge envs from exactly **three** places: the user's environment variables, the user env file (`~/.config/griptape_nodes/.env`) and, …

refactor: greatly simplify config/secrets

---

src/griptape_nodes/__init__.py

Had it backwards, user config was taking precedence over workspace config.

Show Config Precedence

---

pyproject.toml
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
uv.lock

This PR removes `pydantic_settings` from the project. I constantly found myself fighting it, suggesting it was the wrong tool for the job. I've replaced it with good ol' json parsing and standard pydantic models.
The issue that drove me over the edge was merging configs. The higher precedence config file's default values were overriding the lower precedence config file's fields.
Closes #424

refactor: remove pydantic settings from config parsing

---

nodes/griptape_nodes_library/agents/base_agent.py
nodes/griptape_nodes_library/agents/create_agent.py
nodes/griptape_nodes_library/agents/run_agent.py
src/griptape_nodes/machines/node_resolution.py

Refactors `create_agent.py` and `run_agent.py` to take advantage of background processing when streaming. I really don't love this syntax and it's further proof that we should implement `asyncio`'s event loop instead of our own so that we can take advantage nicities like `async for`.
Closes #400

feat: enable background work for agent nodes

---

nodes/griptape_nodes_library/agents/base_agent.py
nodes/griptape_nodes_library/agents/create_agent.py
nodes/griptape_nodes_library/rules/ruleset_list.py
nodes/griptape_nodes_library/tools/tool_list.py

Makes the usage of `RulesetList` consistent with the implementation `ToolsList` which fixes them not resolving.
Note that there is a minor regression in that you can no longer attach a single Ruleset directly. This is the same problem with any `ParameterList` field so we should track it separately: https://github.com/griptape-ai/griptape-nodes/issues/473.
Closes #433
Closes #434

fix: correctly handle rulesets

---

src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Closes #507 
Without app.py echoing what the exception was, I would have gone crazy figuring this out. It led me to where the problem was: we were only catching one specific type of exception during library loading. Expanded with a catch-all.

Echo exceptions at app level and handle all exceptions for library loading

---

nodes/griptape_nodes_library/image/create_image.py

Last bit of fixes for #489. Streaming causes the text chunks to go into the image display because the parameter is named `output` and we [hardcode](https://github.com/griptape-ai/griptape-vsl-gui/blob/ec28559e1671fbc16bf5b38e143db79b4a7d03e3/src/components/FlowEditor.tsx?plain=1#L1073-L1075) handle that in the UI. Long term, `ProgressEvent`s will be a more robust solution here.
Closes #489
Closes https://github.com/griptape-ai/griptape-vsl-gui/issues/311 
Closes https://github.com/griptape-ai/griptape-vsl-gui/issues/309
Closes https://github.com/griptape-ai/griptape-vsl-gui/issues/310
Closes https://github.com/griptape-ai/griptape-vsl-gui/issues/317

Image Generation Fixes

---

pyproject.toml

TBH I don't understand why pyright isn't catching this one. But seems fine enough as a workaround.
```
make check
158 files already formatted
nodes/griptape_nodes_library/tools/date_time_tool.py:4:1: TID251 `nodes.griptape_nodes_library` is banned: Import from griptape_nodes_library instead of nodes.griptape_nodes_library
|
3 | from griptape_nodes_library.tools.base_tool import BaseTool
4 | from nodes.griptape_nodes_library.tools.base_tool import BaseTool
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TID251
|
```
Closes #514

chore: add lint rule for nodes.griptape_nodes_library import

---

src/griptape_nodes/retained_mode/events/connection_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Requests that can reasonably be run within a node context now take `node_name` as optional. Will attempt to use the Current Context if so.

---

src/griptape_nodes/machines/node_resolution.py

Previously exceptions in the background thread would go uncaught putting us in an awkward position. Now we catch them.

fix: safely handle exceptions that happen in the background

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/machines/node_resolution.py

Ensures nice cleanup when the flow is cancelled

fix: move process_generator from node to resolution machine context

---

src/griptape_nodes/app/app.py

Turns out the UI needs this to listen on side effects.
Needed for https://github.com/griptape-ai/griptape-vsl-gui/pull/477

revert: don't suppress requests without request_id

---

src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Refactor `process_generator` and `scheduled_value` to live on the `focus_stack`. May help scenarios where there are many overlapping background processes.

refactor: move process_generator from node to resolution machine context (#580)

---

pyproject.toml
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/griptape_nodes.py

When a library is attempted to be loaded, we don't stop at the first error any longer. This attempts to collate ALL errors. This can eventually be surfaced in the UI but for now we emit a Panel table on startup.

Collate all problems on library load. Classify for good, flawed, unusable, or missing.

---

src/griptape_nodes/machines/node_resolution.py

- Updating node resolution so that when a node is re-resolved, it deletes all of the currently generated output values. This should prevent the output from runs appending on each other, or holding onto images from previous runs. 
- I moved clearing output values out of on_enter to simplify the method, so I created a new helper function on ExecuteNodeState. 
- the only difference in functionality is this line:
```
if parameter_name in current_node.parameter_output_values:
del current_node.parameter_output_values[parameter_name]
```
closes #598

Clear output Values

---

src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- Updated the flow_queue to correctly grab the right nodes to start and continue through the flow. It was grabbing the incorrect first nodes without control connections
- moved the logic for starting the next start node (if there's multiple, disconnected nodes in the canvas) into ControlFlow instead of sending a request, because that wasn't working with the new lambda yielding. 
closes #609 
closes #550

Fix Flow Resolution

---

src/griptape_nodes/exe_types/node_types.py

- The value for the ruleset wasn't updating when I changed the ruleset itself.
- It was holding onto the value for the ruleset list, and wasn't taking the new items in the list into account. 
- closes #624

Fixing Ruleset resolution

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Added some hints to rich to prevent file paths from being truncated in the Panels shown at startup.

Prevent file paths from being truncated in Library and Workflow Info panels

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

also fixed the haunted lint print

Connection virtual functions in BaseNode were using `Self`, but that meant derived classes weren't able to override those functions correctly.

---

src/griptape_nodes/retained_mode/griptape_nodes.py

A RegisterWorkflowRequest that comes from the engine has all the right types, but an event that comes from the editor has metadata with type `dict`, causing all sorts of type issues down the call stack. This change checks if metadata is a dict and creates a WorkflowMetadata from that information if so.

Create WorkflowMetadata from request input

---

CONTRIBUTING.md
src/griptape_nodes/app/app.py

We are not resilliant against changing ports since we save the full url (with the port) of static files. Long term we may want to investigate some sort of local domain. Picked a random port outside the crowded dev server cluster (3000, 5000, 8000, 8080)
Reverts https://github.com/griptape-ai/griptape-nodes/pull/657

revert: don't use OS-assigned port number

---

.github/workflows/pull-request-links.yml

Fixes RTD preview links by removing settings that were specific to the framework.
----
📚 Documentation preview 📚: https://griptape-nodes--688.org.readthedocs.build/en/688/

fix: specify language in RTD previews

---

src/griptape_nodes/retained_mode/events/config_events.py
src/griptape_nodes/retained_mode/managers/config_manager.py

Provide the editor with the ability to query the path to the config (settings?) file the engine is currently using.

Add request/response for config path

---

src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Stepping stone towards #555 
Once we have these as a list, we can now interrogate metadata directly for `is_template` and use this to save templates as COPIES of workflows in the customer's directory.

Registered workflows are now a list and not a dict. WARNING: Requires a config reset for now.

---

src/griptape_nodes/retained_mode/events/config_events.py

Super quick change to indicate that the get config events are guaranteed not to alter the workflow.

Indicate GetConfig as read-only guarantee

---

src/griptape_nodes/__init__.py

fix: don't barf config when running config list

---

src/griptape_nodes/exe_types/node_types.py

Fixes #711 
Save files are broken if a Parameter with a space appears in it. We have #714 to remedy this.

Raise error if space detected in Parameter name

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py

From my testing it appears this is not needed and solves the immediate problem.
Closes #702

fix: don't resume processing when cancelling

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Closes #555 
If the user attempts to save a workflow that is a template, it will instead generate a new workflow in the customer's workspace directory with a non-colliding file name.

Template files generate workflows when save attempted.

---

src/griptape_nodes/retained_mode/managers/flow_manager.py

Closes #730 
Verify that a Parameter actually had a value before attempting to remove it during disconnect. The `remove_parameter_value` call would generate a warning that was distressing during rehearsals.

don't try to remove values where no values exist; it generates errant warnings.

---

src/griptape_nodes/retained_mode/managers/node_manager.py

This can happen if the user saves the workflow while it's resolving. The resolving state is persisted in the script file and respawns the flow in a wonky state on subsequent runs.
```python
GriptapeNodes.handle_request(
CreateNodeRequest(
request_id=None,
node_type="AgentToTool",
specific_library_name=None,
node_name="AgentToTool_1",
override_parent_flow_name="untitled",
resolution="resolving",
initial_setup=True,
set_as_new_context=False,
)
)
```
Closes #733 
This ^ was happening because the previous node would not resolve and so the values were all garbled. There is probably some future work to be done to more gracefully handle wonky scenarios like this.

fix: don't allow new nodes to be created in a resolving state

---

src/griptape_nodes/exe_types/type_validator.py

Original issue came from:
```
ERROR    Error serializing object: Going to use type name.
╭─────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────╮
│ /Users/collindutter/Documents/griptape/griptape-nodes/src/griptape_nodes/exe_types/type_validator.py:30 │
│ in safe_serialize                                                                                       │
│                                                                                                         │
│   27 │   │   if isinstance(obj, (str, int, float, bool, list, dict, type(None))):                       │
│   28 │   │   │   return obj                                                                             │
│   29 │   │   try: …
```

fix: make safe serialize even safer

---

CONTRIBUTING.md
Makefile

As of `uv>=0.7.1` there is now a dedicated version interface which means we can remove the hacky toml parsing.

refactor: use new uv version interface

---

src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py

This PR brings two changes:
1. Check the existence of a running flow before attempting to cancel it. [#750](#750) suggests that we may want to suppress the error, but I think it's better that we instead safely check.
2. Rearrange some of the error/exception logs such that exceptions in nodes produce a stack trace. Previously these were being suppressed while confusing engine internals were being shown. Logs now look like:
```
ERROR    Error processing node 'LoadImage_1': Image is not set
╭─────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────╮
│ /Users/collindutter/Documents/griptape/griptape-nodes/src/griptape_nodes/machines/node_resolution.py:25 │
│ 2 in on_update …
```

Cancellation/Error Improvements

---

nodes/griptape_nodes_library/image/load_image.py
nodes/griptape_nodes_library/image/save_image.py
nodes/griptape_nodes_library/utils/image_utils.py

The UI sends over this:
```
cmd.set_value("LoadImage_1.image",value="{'value': 'http://localhost:8124/static/1498DAE5-AAA7-44AA-8EF9-FC51F42AD140_1_105_c.jpg', 'type': 'ImageUrlArtifact', ...some more...)
```
The node was properly handling this when type was `ImageArtifact`, but broke when that was changed on the UI.
Closes #754

fix: handle dictionaries that look like image url artifacts

---

src/griptape_nodes/retained_mode/events/app_events.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/events/config_events.py
src/griptape_nodes/retained_mode/events/connection_events.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/events/library_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/events/object_events.py
src/griptape_nodes/retained_mode/events/os_events.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/events/secrets_events.py
src/griptape_nodes/retained_mode/events/static_file_events.py
src/griptape_nodes/retained_mode/events/validation_events.py
src/griptape_nodes/retained_mode/events/workflow_events.py

Contains a few changes to ensure the `altered_workflow_state` flag actually makes it to the serialized response payload.
Inheritance order and decorators make all the difference here. Without them, the Python objects will report the correct `altered_workflow_state` attribute value as set by the mixin, but it won't end up in the JSON. We love Python, don't we, folks?

Fix altered workflow result flag

---

docs/faq.md
pyproject.toml
src/griptape_nodes/__init__.py
src/griptape_nodes/updater/__init__.py

This PR overhauls a few components:
1. The argument parsing has been rewritten/restructured to have a cleaner top level namespace.
Engine and asset update commands have been moved into `gtn self update` and `gtn assets update` respectively.
``` ❯ gtn --help usage: griptape-nodes [-h] [--no-update] COMMAND ...
Griptape Nodes Engine.
positional arguments:
COMMAND
init       Initialize a workspace.
engine     Run the Griptape Nodes engine.
config     Manage configuration.
self       Manage this CLI installation.
assets     Manage local assets (workflows, libraries, etc.).
options:
-h, --help   show this help message and exit
--no-update  Skip the auto-update check.
```
2. The engine updater has been moved into a dedicated executable (`griptape-nodes-updater`). When performing an engine …

refactor: separate updater into dedicated process

---

src/griptape_nodes/traits/compare_images.py

Does not fix #753 but gets rid of errors

fix: use correct keys for validation in compare image

---

docs/faq.md
docs/reference/command_line_interface.md
src/griptape_nodes/__init__.py

The implicit subcommand behavior of `gtn config` was inconsistent with other commands

refactor!: change `gtn config` to `gtn config show`

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/secrets_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Reload secrets after settings them.
Secrets file takes precedence over system environment variables.
Removed stray `load_dotenv`s.
Closes https://github.com/griptape-ai/griptape-vsl-gui/issues/559

Secret Improvements

---

nodes/griptape_nodes_library_extras.json

Changed name. Separate issue coming in for moving the path and renaming the library.json to be correct.

Rename to "Griptape Nodes Advanced Image Library" (GNAIL)

---

src/griptape_nodes/retained_mode/managers/settings.py

Closes #904 
Reordered template workflows to have parity with https://docs.griptapenodes.com/en/stable/

Reorder to match docs

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py

This fixes a regression introduced in #916.
Previously, libraries_to_register was retrieved from the fully merged config, which included both user and default values. After recent changes, we now access only the user config directly—causing issues during new user installs, where libraries_to_register is not yet defined.
This change restores expected behavior by checking the default config when the value is missing in the user config.

fix: fall back to default config when getting config value

---

src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Every now and then I've noticed the rich handler not being used:
```
[05/03/25 15:36:44] INFO     Resolving GenerateImage_1
INFO:griptape_nodes:Resolving GenerateImage_1
INFO     Node TextInput_1 is processing.
INFO:griptape_nodes:Node TextInput_1 is processing.
INFO     Node TextInput_1 finished processing.
INFO:griptape_nodes:Node TextInput_1 finished processing.
INFO     TextInput_1 resolved.
INFO:griptape_nodes:TextInput_1 resolved.
```
I'm not quite sure what triggers this, but this PR centralizes the handlers. Maybe it'll help.

refactor: move rich handler to app

---

src/griptape_nodes/__init__.py

These imports can take quite a while due to some cascading imports in griptape. While we tackle that issue separately, this at least gives some indication of progress to the user.
Progress towards #931

feat: show spinner while loading expensive imports

---

src/griptape_nodes/__init__.py
src/griptape_nodes/app/nodes_api_socket_manager.py

Turns out if you paste in a REALLY bad api key the server throws a 500. This was silently failing in a loop. Updated our error handling to cover more cases.
PR also tweaks/adds some messaging.
Closes #971
Closes #973
Closes #969

fix: handle more status codes when connecting to API

---

src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/managers/library_manager.py

Expanded the library schema to include custom, per-library settings. For example, in the griptape_nodes_library.json file:
```
{
"name": "My Cool Library",
"library_schema_version": "0.1.0",
<SNIP>
"settings": [
{
"description": "Environment variables for storing secrets for new AI service's nodes",
"category": "nodes.TheCoolestServiceOnTheBlock",
"contents": {
"TCSOTB_ACCESS_KEY": "$TCSOTB_ACCESS_KEY", 
"TCSOTB_SECRET_KEY": "$TCSOTB_SECRET_KEY" 
}
}
]
}
```
It seems to play nice with secrets, too.

Added ability to define new settings within a node library.

---

CONTRIBUTING.md
src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/events/static_file_events.py
src/griptape_nodes/retained_mode/managers/event_manager.py

This PR makes two key changes:
1. Updates the fastapi static server to act as an event source. The UI can [take advantage of](https://github.com/griptape-ai/griptape-vsl-gui/pull/648) this by sending heavy events like `CreateStaticFilesRequest` over this local channel. These events will be processed like any other event from the server and the results will be sent over the regular event server.
2. Adds the ability for requests to mark certain fields as `omit_from_result`. These fields will be cleared out on the request before it goes back with the result.
Open question: should all events work this way? UI -> local -> API -> UI
Closes #1006
Closes #947

feat: accept request events on local static server

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py

Adding an item to the parameter list leaves it populated with an empty list. i.e. `[[]]`. This fails when passing to the agent.
Long term might be better to find a better initial value?
Closes #1048

fix: verify parameter lists are populated

---

src/griptape_nodes/exe_types/node_types.py

closes #852 
Just had to delete `valid_or_fallback` method since it wasn't being used anywhere else.

Remove valid or fallback method

---

.github/workflows/latest-release.yml
.github/workflows/stable-release.yml
Makefile
README.md

- Drop "nightly" in favor of RTD-friendly "latest"
- Replace latest doc links with stable

refactor: clean up use of release tags

---

src/griptape_nodes/__init__.py
src/griptape_nodes/updater/__init__.py

- Sync the assets from your current engine version rather than latest. 
- Clear out assets directory before copying over. Ensures no stray library data.
- Run asset sync during `gtn self update`.
Closes #1034

feat: sync assets based on current engine version

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/griptape_nodes_library/config/base_driver.py
libraries/griptape_nodes_library/griptape_nodes_library/config/image/grok_image_driver.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/amazon_bedrock_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/anthropic_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/base_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/cohere_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/griptape_cloud_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/grok_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/openai_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/node_manager.py
tests/integration/retained_mode/events/test_node_events.py
tests/unit/exe_types/test_core_types.py

closes #412 
Adds a remove parameter by name method to `BaseNode`, and updates methods to remove elements by name instead of specifically parameters. (this now includes ParameterGroups, ParameterContainers, and Traits) 
Changes group to have the field `name` instead of `group_name` to keep it consistent across Parameters and ParameterGroups

Refactor: Updating methods on nodes to be more generalized

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/griptape_nodes_library/workflows/__init__.py
libraries/griptape_nodes_library/griptape_nodes_library/workflows/library_style.json
libraries/griptape_nodes_library/griptape_nodes_library/workflows/published_workflow.py
src/griptape_nodes/bootstrap/__init__.py
src/griptape_nodes/bootstrap/bootstrap_script.py
src/griptape_nodes/bootstrap/structure_config.yaml
src/griptape_nodes/retained_mode/events/workflow_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Initial commit for publish workflow event
* Handle `PublishWorkflowRequest` in engine
* Bundle a workflow into a zip
* Deploy the zip through the Nodes API to GTC, submitting workflow_name as well as input/output shapes to the API
* PublishedWorkflow Node capable of being configured with a workflow_id, and used as a ControlNode within a Flow to invoke the hosted Workflow with input Parameters, and return values for the output Parameters
Closes #356 
Closes #765 
TODO
---
* Handle bundling libraries properly. Right now, only default libraries are included
* Frontend fixes for dynamically creating Parameters resulting from `after_value_set` callback
* Frontend fixes for Parameter Options to handle option choices of a different type than their value after conversion
Issues
---
* It seems …

Initial commit for publish workflow event

---

src/griptape_nodes/__init__.py

On windows there is still a noticable delay on first startup from importing packages. This moves the spinner up earlier to capture all imports.

fix: show loader earlier

---

src/griptape_nodes/app/app.py

The engine is fine, no need to completely re-init it.

fix: don't re-init engine on SSE error

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Set published workflow ID in metadata
* When a Workflow is published, save the ID in the workflow script metadata
* This can be used to update an existing workflow when the workflow is published again
Closes #1105 
https://www.loom.com/share/0770e81665614525b587eee850d6ebac?sid=d19ca370-1e2c-4e60-a9de-d1b6348b314a

Set published workflow ID in metadata

---

libraries/griptape_nodes_library/griptape_nodes_library/utils/error_utils.py

Kyle hit an issue where `message` wasn't defined. I figured we might as well make this whole function safer/less assumptive

Handle unexpected error message shapes

---

src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Closes #1165 
You can still run code like this in the editor:
```
from griptape_nodes.retained_mode.events.flow_events import SerializeFlowToCommandsRequest, DeserializeFlowFromCommandsRequest
serialized_flow_request = SerializeFlowToCommandsRequest(include_create_flow_command=False)
serialized_flow_result = api.handle_request(serialized_flow_request)
deserialized_flow_request = DeserializeFlowFromCommandsRequest(serialized_flow_result.serialized_flow_commands)
deserialized_flow_result = api.handle_request(deserialized_flow_request)
```
...but now we'll be able to look up by UUID, which is necessary for reliable codegen and portable copy/paste/duplicate.

Convert serialization's index-based mapping of connection and parameter value to UUID-based.

---

src/griptape_nodes/exe_types/type_validator.py
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/payload_registry.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/traits/trait_registry.py
src/griptape_nodes/utils/metaclasses.py

In some places we used `SingletonMeta`, in others we used griptape's `SingletonMixin`. This PR standardizes on the `SingletonMeta`.  In general we should avoid using the more "internal" aspects of griptape.

refactor: remove reliance on griptape's SingletonMixin

---

libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py

I noticed an small detail in the describeImage node, where the output was called "image description" instead of "output." This could likely make it more confusing for users and it is much more straightforward to simply call it "output." I have made a pull request so that this can be fixed.

change output name of describeImage node

---

libraries/griptape_nodes_library/griptape_nodes_library/audio/microphone.py

This mirrors the webcam node by providing access to a device's microphone via the browser APIs to gather audio data.

Add microphone node

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
src/griptape_nodes/exe_types/node_types.py

There was a bug that would allow a ruleset_list to be connected to a single ruleset item.
Instead of removing that functionality, I errored on giving the agent the ability to handle it better by creating a new method `get_parameter_list_value`.
This will returned a flattened list of items from a ParameterList in case someone does something like:
`input_types=["Ruleset", "List[Ruleset"]`
and just wants it as a flat list.
fixes: #1096

add method to get a flat ParameterList

---

libraries/griptape_nodes_library/griptape_nodes_library/rules/create_ruleset.py

e.g.
```
Rule 1
More of Rule 1
Rule 2
More of Rule 2
```

fix: use \n\n as rule delimiter to allow for rules across multiple lines

---

libraries/griptape_nodes_library/griptape_nodes_library/audio/load_audio.py
libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py

Quick two line changes to prevent the LoadImage and LoadAudio nodes from breaking when they are not set.

Fix Audio and Image Node

---

src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/context_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/object_manager.py

closes #1153 
Creates several new events:
`SerializeSelectedNodestoCommandsRequest` which takes a list of the node names and the timestamp they were selected.
`DeserializeSelectedNodesFromCommandsRequest` which takes no parameters. 
`DuplicateSelectedNodesRequest` which takes a list of the node names and the timestamp they were selected.
For Cmd C - `SerializeSelectedNodestoCommandsRequest`, which copies
For Cmd V -`DeserializeSelectedNodesFromCommandsRequest`, which pastes
For Cmd D- `DuplicateSelectedNodesRequest` which copies and pastes together. 
These should allow all selected nodes, their parameter values, and their connections between each other to be serialized and deserialized on paste.

Allow for Duplication of Nodes

---

src/griptape_nodes/bootstrap/bootstrap_script.py
src/griptape_nodes/bootstrap/post_build_install_script.sh
src/griptape_nodes/bootstrap/pre_build_install_script.sh
src/griptape_nodes/bootstrap/register_libraries_script.py
src/griptape_nodes/bootstrap/structure_config.yaml
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Support libraries for published workflows
* Copy over library file tree
* Register libraries at build time to handle dependency installation
* Fix file path traversal
* Enable publish workflow to utilize engine version from a specific commit, rather than just a git tag version
Closes #951 
https://www.loom.com/share/82e0194e33c24cc58c045b09be8eb849?sid=8545d2c3-f1cf-46e4-994c-c8b9c1968922

Support libraries for published workflows

---

src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Stores rejected hash values, too, to prevent unnecessary serialization attempts of large values. Wraps it into a class.

---

src/griptape_nodes/retained_mode/managers/node_manager.py

closes #1200 
When saving a workflow, it saves resolution state so you can pick up where you left off:
without running the whole workflow.

Save Resolution State

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/seed_parameter.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_parameters.py

Adding a "randomize_seed" toggle to the flux pipelines.
If randomize_seed is false, has an input pin and is editable.
If randomize_seed is true, has no input pin, is not editable, and generates a new seed at the start of a run. The new seed is displayed for reproducibility and also supplies an output pin for chaining.
Amaru approved in slack, but I'll add him here too.
I want to merge this despite the following caveats because the feature is usable and still better than current CX (even with the bugs):
- ~~https://github.com/griptape-ai/griptape-nodes/issues/1233~~  
fixed by https://github.com/griptape-ai/griptape-vsl-gui/pull/758
- https://github.com/griptape-ai/griptape-nodes/issues/1234
Resolves #1215

Add randomize seed flags to flux pipelines

---

pyproject.toml
src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/events/static_file_events.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py
uv.lock

This PR adds two new endpoints to the static server:
- `PUT /static-uploads/{file_name:str}`: Accepts a file to upload and saves it to the static files directory. Technically clients can interact with this endpoint directly but it is recommended to use the `/static-upload-urls` first.
- `POST /static-upload-urls`: Generates a URL to the `/static-uploads` endpoint.
A new event has been added to interact with the `static-upload-url` endpoint:
- `CreateStaticFileUploadUrlRequest`
Today the only upload backend we support is the engine's endpoints, but this could be easily generalized for other services (GTC, S3, etc.).
To interact with this endpoint, the caller (UI) will:
1. Make a request to this endpoint to receive a static upload URL. The static upload URL will be specific to the upload …

feat: add events for uploading to static server via URL

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Somehow the engine version is being misreported. Presumably from a library that installs `griptape-nodes`. Terrifying. This PR makes it so the engine version is collected at the very start.

fix: determine engine version before runtime deps are installed

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

AlterParameterEvent now has values. This fixes the bug that Jason had issues with, where after removing a connection didn't update prompt model in the Agent node. 
closes #1267 
Still needs a bit more work to add parameters on these events.

Update AlterParameterEvent to contain values

---

src/griptape_nodes/__init__.py

Currently, you can't `init` with flags alone because of `--register-advanced-library`. There's no way to pass a falsy value to this step.
Refactor `--register-advanced-library` to accept `true` | `false` values.
Default arg values to `GTN_{ENV}` values.

fix: correctly parse args on fresh install

---

libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py

Was much simpler than we thought. Just meant doing some surgery on the conversation memory in the describe image node to prevent the base64 from being serialized. 
I checked other image nodes in the griptape nodes library (not advanced media library) using agents and didn't see any other examples that need this conversation memory surgery, so this was the only one I modified. 
closes #1306

Prevent base64 in Conversation Memory

---

src/griptape_nodes/__init__.py

Workaround for #1302
None of the [hacks](https://stackoverflow.com/questions/2656322/shutil-rmtree-fails-on-windows-with-access-is-denied) mentioned worked for me. Not worth spending too much time on right now.

fix: add uninstallation caveat when removing config/data dirs

---

src/griptape_nodes/drivers/__init__.py
src/griptape_nodes/drivers/storage/__init__.py
src/griptape_nodes/drivers/storage/base_storage_driver.py
src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/drivers/storage/local_storage_driver.py
src/griptape_nodes/retained_mode/events/static_file_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

Now users can specify whether they'd like to upload files using the local static server (default), or use Griptape Cloud. The main advantage of using Griptape Cloud being that the engine can run on a separate machine from the UI.
Don't merge yet, there are some timing considerations with the UI.

feat: add support for multiple storage backends

---

src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

This was leading to a race condition which caused multiple buckets to be provisioned. This is a semi-advanced use-case, we can include this in documentation for multi-machine setups.
Related #1332

fix: remove automatic bucket provisioning

---

src/griptape_nodes/app/app.py
src/griptape_nodes/drivers/storage/base_storage_driver.py
src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/drivers/storage/local_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

Moves driver-specific logic for creating static files out into the manager. This is more consistent with how the UI makes its operations.
Also refactors our static server to use the body as the upload contents, rather than an explicit "file" field. This is more consistent with how other pre-signed urls work.
Together these fix an issue with nodes calling `save_static_file`

fix: correctly save static files

---

src/griptape_nodes/bootstrap/bootstrap_script.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/retained_mode/managers/context_manager.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

ContextManager now uses objects instead of names. This will make renaming less damaging, and paves the way for us to begin to track objects separately from their names.
- For `node()`, `flow()`, and `element()`, you can still use name as a `str`, so workflow saving and loading still works with `with ContextManager().node()`, since creating objects in the python save files is extra work. 
- For `ControlFlow` objects, I added `.name` as a field. In a future PR I will update other cases where `.name` will be useful, but it seemed like flows should store their own names since nodes and elements do.

Update ContextManager to Track Objects

---

src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/object_manager.py

Nodes can now be renamed without breaking everything.
Renames them in their flows, connections, and nodes themselves. 
closes #1108

Making Nodes Renameable Again

---

libraries/griptape_nodes_library/workflows/templates/compare_prompts.py
libraries/griptape_nodes_library/workflows/templates/coordinating_agents.py
libraries/griptape_nodes_library/workflows/templates/photography_team.py

Standard node library's templates were resaved with an "_1" suffix; removed that.

---

src/griptape_nodes/retained_mode/managers/node_manager.py

Will not mark a node as unresolved if the new value is the same as the old value.

Prevent unnecessary dirtying of nodes

---

src/griptape_nodes/__init__.py
src/griptape_nodes/bootstrap/bootstrap_script.py
src/griptape_nodes/bootstrap/workflow_runners/local_workflow_runner.py
src/griptape_nodes/bootstrap/workflow_runners/subprocess_workflow_runner.py
src/griptape_nodes/bootstrap/workflow_runners/workflow_runner.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Support gtc storage for published workflows
* The bootstrap script now accepts `--storage-backend` flag for specifying a storage type
* The RunPublishedWorkflow API will handle setting that flag
* Handle failed workflow runs
* Previously, a failed workflow run would report the correct events back to the Nodes API, but it would get stuck in an endless loop for the underlying StructureRun. Handle this by listening to the `ControlFlowCancelledEvent` event
* Allow various Parameter types for PublishedWorkflow StartNode and EndNodes
* Explicitly ignoring `list` types for now due to the strangeness with our current  [StartFlow and EndFlow Nodes](https://github.com/griptape-ai/griptape-nodes/blob/main/libraries/griptape_nodes_library/griptape_nodes_library/workflows/start_flow.py#L18) making …

Support gtc storage for published workflows

---

libraries/griptape_nodes_advanced_media_library/controlnet_aux_nodes_library/anyline_detector.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/flux_control_net_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_one_flux_control_net_model.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_two_flux_control_net_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/tiling_flux_img_2_img_pipeline.py
libraries/griptape_nodes_advanced_media_library/opencv_nodes_library/canny_convert_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/gaussian_blur_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/grayscale_convert_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/rescale_image.py
libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/tiling_span.py
libraries/griptape_nodes_advanced_media_library/transformers_nodes_library/depth_anything_for_depth_estimation.py
libraries/griptape_nodes_advanced_media_library/utils/__init__.py
libraries/griptape_nodes_advanced_media_library/utils/image_utils.py
libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py
libraries/griptape_nodes_library/griptape_nodes_library/image/save_image.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/image_utils.py

Added friendlier error message if image URL failed to download. Happens with shared workflows or if staticfiles gets wiped.

---

docs/command_line_interface.md
docs/faq.md
src/griptape_nodes/__init__.py
src/griptape_nodes/updater/__init__.py

- Rename `gtn assets sync` to `gtn libraries sync`. "Assets" is not a term we use anywhere else, let's be honest about what it is.
- Init the libraries during `gtn libraries sync`. This enables library troubleshooting/set-up to be done without booting up the engine.
- Don't blow away existing libraries in the libraries directory when syncing.
Closes #1504 
Closes #1509

Libraries sync

---

src/griptape_nodes/drivers/storage/local_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

https://github.com/griptape-ai/griptape-nodes/pull/1471 was done incorrectly. We only want this for local storage driver.

fix: only cache bust local storage driver

---

libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py
uv.lock

Verified that an example of one of the failing nodes (depth anything v2 for images) not built to accept dicts succeeds again.
Also, version bump in uv.lock wasn't previously commit (expand diff to see I'm not adding deps or anything crazy)

Don't return dict from LoadImage

---

src/griptape_nodes/exe_types/node_types.py

- Prevents events from being emitted for the list when a child within a list changes. This extra emission is unnecessary because the change will already be emitted from the child parameter.
- closes #1593 
- This could be because we're handling events incorrectly in the editor, since the list event was being sent with the correct information and was overriding in an incorrect way. However, this will fix the issue quickly. Could be worth going back to the gui and figuring out why it isn't working in the future.

Fix Modified ParameterList Bug

---

src/griptape_nodes/app/__init__.py
src/griptape_nodes/app/app_sessions.py
src/griptape_nodes/retained_mode/events/app_events.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/utils/__init__.py
src/griptape_nodes/retained_mode/utils/engine_identity.py
src/griptape_nodes/retained_mode/utils/name_generator.py
src/griptape_nodes/retained_mode/utils/session_persistence.py

This PR introduces new event types and architectural changes to support a comprehensive overhaul of session management in both the API and UI.
**AppStartSessionRequest**
- **Breaking Change**: No longer accepts `session_id` in the request body
- Session IDs are now generated server-side by the engine rather than client-side
**AppEndSessionRequest**
- New event type for properly terminating sessions with an engine
**SessionHeartbeatRequest**
- Enables clients to maintain connection health with the engine after session establishment
- Replaces previous ad-hoc heartbeat mechanism
**EngineHeartbeatRequest**  
- Allows sessionless clients to discover and connect to available engines
- Response includes comprehensive engine metadata for client decision-making
**SetEngineNameRequest / …

feat: overhaul sessions

---

src/griptape_nodes/retained_mode/managers/library_manager.py

This update reduces the saturation of the sandbox library, and also lets the user define ICON, COLOR, and DESCRIPTION as class attributes in their nodes if they want.
fixes: https://github.com/griptape-ai/griptape-vsl-gui/issues/970

update: Sandbox Color and user icons

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Remove error logs that occur during workflow save
*  These aren't needed. Whatever is calling `_extract_workflow_shape` can handle the errors as needed

Remove error logs that occur during workflow save

---

src/griptape_nodes/node_library/advanced_node_library.py
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/managers/library_manager.py

Create a file in your library called `my_cool_library.py` and put the following in it:
```
"library_schema_version": "0.2.0",
"advanced_library_path": "my_cool_library.py",
```
Then define it as such:
```
from griptape_nodes.node_library.advanced_node_library import AdvancedNodeLibrary
class GriptapeNodesLibraryAdvanced(AdvancedNodeLibrary):
"""Advanced library implementation for the default Griptape Nodes Library.
This demonstrates the callback system for library-level initialization.
"""
def before_library_nodes_loaded(self, library_data, library):
"""Called before any nodes are loaded from the library."""
print(f"🚀 Starting to load nodes for '{library_data.name}' library...")
print(f"   Library version: {library_data.metadata.library_version}")
print(f"   Total nodes to load: …
```

Added Advanced Library class for library-level callbacks

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/huggingface_utils.py

Some nodes are making a handful of calls to disk (`huggingface-cli scan-cache`). On the machines we've been primarily using, these calls have been effectively free. On some other machines, each call takes upwards of a second.
This PR implements a variation of the solution mentioned here: https://github.com/huggingface/huggingface_hub/issues/1564#issuecomment-1710764361

perf: implement faster scan of hf_cache

---

install.ps1
install.sh
src/griptape_nodes/retained_mode/managers/library_manager.py

If the user _doesn't_ have uv installed, we install it into the xdg data dir so that cleanup is easy.
Closes #1408

fix: don't install uv if already installed

---

src/griptape_nodes/app/app_sessions.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/managers/engine_identity_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/session_manager.py

This is a mess (thanks claude). Will clean up in a future PR because this will haunt me.
Fixes recursive logs.

fix: change how/where engine_id/session_id are set on events

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Was used so that the editor could know whether the engine was local to this machine. But not worth the feeling of sketchyness.

refactor: remove ip ping

---

libraries/griptape_nodes_library/workflows/templates/compare_prompts.py
libraries/griptape_nodes_library/workflows/templates/coordinating_agents.py
libraries/griptape_nodes_library/workflows/templates/photography_team.py
libraries/griptape_nodes_library/workflows/templates/prompt_an_image.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Pickles were failing and nodes were still 'resolved', which was causing errors in subsequent runs.
Force node to be marked as unresolved.

Force unresolved resolution state if pickle fails

---

src/griptape_nodes/app/api.py
src/griptape_nodes/mcp_server/server.py

Creates unnecessary log noise. Amplified by the fact that we have two servers now (static, mcp).
This PR sets the log level to `ERROR` to avoid showing logs like `Waiting for application startup.`.
Current:
```
❮ make run/watch
uv run src/griptape_nodes/app/watch.py
Checking for updates...
Starting Griptape Nodes engine...
[07/29/25 12:22:51] INFO     Starting MCP GTN server...
INFO:     Started server process [94228]
[07/29/25 12:22:51] INFO     Started server process [94228]
INFO:     Waiting for application startup.
INFO     Waiting for application startup.
INFO:     Started server process [94228]
INFO     Started server process [94228]
INFO:     Waiting for application startup.
INFO     Waiting for application startup.
INFO:     Application startup complete.
INFO     Application …
```

refactor: hide uvicorn logs by default

---

src/griptape_nodes/exe_types/core_types.py

Fixes #1721 
Today, the editor is hard-coding "Flow In" and "Flow Out" and not using the parameter `name` field. 
If we were to flip the editor to always use the parameter `name` field, all control ports would switch to `exec_in` and `exec_out` which isn't very appealing to look at, but would be consistent.
If we were to then change all of our control port parameter names from "exec_in" and "exec_out" to "Flow In" and "Flow Out", all existing flows that used the control ports would break.
The editor does, however, respect the `display_name` field if passed as a ui_option. This change defaults Control In and Control Out to have "Flow In" and "Flow Out" specified as a display name. If the user doesn't specify those, we will be updating the editor to display the parameter name again and get …

Maintain parity with existing control display names without changing underlying parameter names.

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

The workflow rename operation was losing the branched_from metadata because the save process looked for an existing workflow with the new name instead of preserving metadata from the original workflow.
This fix modifies on_save_workflow_request to check for a current workflow context when no prior workflow exists for the new name, ensuring that metadata (including branched_from) is preserved during rename operations.

fix: preserve branched_from metadata during workflow rename

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/option_utils.py

```
[08/05/25 20:51:24] INFO     Installing dependencies for library 'Griptape Nodes Library' with pip in venv at
C:\ProgramData\GriptapeNodes\libraries\griptape_nodes_library\.venv
[08/05/25 20:51:25] INFO     Successfully loaded Library 'Griptape Nodes Library' from JSON file at
C:\ProgramData\GriptapeNodes\libraries\griptape_nodes_library\griptape_nodes_library.json
INFO     Installing dependencies for library 'Griptape Nodes Advanced Media Library' with pip in
venv at C:\ProgramData\GriptapeNodes\libraries\griptape_nodes_advanced_media_library\.venv
[08/05/25 20:51:29] ERROR    Attempted to load node 'DepthAnythingForDepthEstimationImage' from
'C:\ProgramData\GriptapeNodes\libraries\griptape_nodes_advanced_media_library\transformers …
```

fix: use correct imports

---

src/griptape_nodes/retained_mode/managers/node_manager.py

Now that we fetch the params during resolution, we don't want to unresolve the node during resolution.
https://griptape-ai.slack.com/archives/C0876P576SG/p1754510568108759

Do not unresolve a node that is actively resolving on param change

---

libraries/griptape_nodes_library/griptape_nodes_library/lists/display_list.py

`if not list_values` was evaluating as true for an empty list, causing the routine to short circuit prematurely.

Empty lists were early outing.

---

libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py

This was removing non-aesthetic, but essential, presigned url info.

fix: remove :sparkles: aesthetic :sparkles: urls

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py

Fixes #1881 
Previous version used `add()` and `remove()` on the `allowed_modes` set. These don't trigger the change detector. `|` and `-` on the set create a new set object, which triggers the change detector.

Direct set modification didn't trigger change detection.

---

docs/ftue/00_tour/FTUE_00_tour.md

we modified the Add Menu to be brought up by hitting shift+a or double-clicking.
----
📚 Documentation preview 📚: https://griptape-nodes--1891.org.readthedocs.build/en/1891/

Update: Documentation for bringing up the Add menu

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_model_parameter.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/huggingface_repo_file_parameter.py
src/griptape_nodes/app/app.py
src/griptape_nodes/mcp_server/ws_request_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py
src/griptape_nodes/retained_mode/retained_mode.py

I'm sorry
```
The error is still occurring because the Unicode characters themselves are the problem. Even with legacy_windows=True, Rich still tries to
encode those specific Unicode emoji characters (✅, 🟡, ❌, ❓) and Windows cp1252 can't handle them.
The only reliable fix is to replace the Unicode characters with ASCII alternatives:
```

Change status emojis to ASCII

---

src/griptape_nodes/__init__.py
src/griptape_nodes/app/app.py
src/griptape_nodes/utils/version_utils.py

Instead of hanging or providing a lengthy traceback, a simple connectivity check gives a friendly error message to users who are experiencing internet connection issues.

Add a connectivity check

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py

Fixes #1935 
Also flagged it as not settable, so user can't select a new one 😤

Maintain the GenerateImage for serialization by marking it as a PROPERTY, not just OUTPUT.

---

src/griptape_nodes/retained_mode/managers/node_manager.py

Fixes #1940 
Calls library manager directly instead of using a request.

Eliminate spoopy error toasts when saving a workflow with error placeholder nodes in place.

---

src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/retained_mode.py

New `BatchSetNodeMetadata` event to help us process multiple node metadata updates at the same time
Closes #1952 
Needs to go in before https://github.com/griptape-ai/griptape-vsl-gui/pull/1210

BatchSetNodeMetadataRequest

---

pyproject.toml
src/griptape_nodes/retained_mode/managers/agent_manager.py
uv.lock

Was hoping for a more async-ey approach here but unfortunately converting a generator to an async generator is [non-trivial](https://stackoverflow.com/questions/77441269/how-to-convert-a-python-generator-to-async-generator).

fix: use async-aware version of griptape

---

libraries/griptape_nodes_library/griptape_nodes_library/text/create_multiline_text.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Fixes #1959 
If a customer supplies an incoming connection to a Parameter that supports the INPUT and PROPERTY, we should reject calls to set the property value directly. It should be listening directly to the incoming connection. Once the incoming connection is removed, we can again accept set value requests.
Note that this approach does NOT modify the `settable` member var on the Parameter, so we're not juggling state.

Reject SetParameterValueRequests on parameters with an incoming connection (except for the value from the connection, of course!)

---

src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/managers/node_manager.py
tests/unit/exe_types/test_core_types.py

Fixes #1966 
Fixes #1979 
Allows user to get, alter, and create parameters with `settable=True` or `False`
If a new (empty) node is connected, propagate None and empty values, too.

Add `settable` as a field for AddParameterToNode, GetParameterDetails, and AlterParameterDetails request types.

---

src/griptape_nodes/bootstrap/workflow_executors/local_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_executors/workflow_executor.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py
tests/unit/bootstrap/__init__.py
tests/unit/bootstrap/workflow_executors/__init__.py
tests/unit/bootstrap/workflow_executors/test_workflow_executor.py

* Update generated workflow executor code for async changes
Old executor code:
```python
def execute_workflow(input: dict, storage_backend: str='local', workflow_executor: WorkflowExecutor | None=None) -> dict | None:
_ensure_workflow_context()
workflow_executor = workflow_executor or LocalWorkflowExecutor()
workflow_executor.run(workflow_name='ControlFlow_1', flow_input=input, storage_backend=storage_backend)
return workflow_executor.output
if __name__ == '__main__':
parser = argparse.ArgumentParser()
parser.add_argument('--storage-backend', choices=['local', 'gtc'], default='local', help="Storage backend to use: 'local' for local filesystem or 'gtc' for Griptape Cloud")
parser.add_argument('--json-input', default=None, help='JSON string containing parameter values. Takes precedence over …
```

Update generated workflow executor code for async changes

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

ControlParameters have settable=False on them and shouldn't be subject to propagation. Fixes an issue where connections would propagate and throw a SetValue error.

Don't propagate values to control params as they don't have any.

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/workflow_events.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py
tests/unit/conftest.py
tests/unit/node_library/__init__.py
tests/unit/node_library/test_workflow_registry.py
tests/unit/retained_mode/managers/test_workflow_manager.py

Importing a workflow will register the workflow wherever it currently lives on disk. This is useful if you want to editor workflows that may live outside the workspace.
This PR also changed save workflow request to not blindly save workflows into the workspace and instead respect their current location.

feat: add import workflow request

---

src/griptape_nodes/retained_mode/managers/event_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Add asyncio fallback for sync event handler
* This is muy bien for the LocalExecutor
* Make use of the `ReloadAllLibrariesRequest` for LocalExecutor library loading, which takes advantage of the asyncio event handler fallback

Add asyncio fallback for sync event handler

---

docs/nodes/three_d/load_gltf.md
libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/three_d/load_three_d.py
libraries/griptape_nodes_library/griptape_nodes_library/three_d/three_d_artifact.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/three_d_utils.py
mkdocs.yml

fixes: https://github.com/griptape-ai/griptape-nodes/issues/1710
Adding a three_d node instead of gltf node, but keeping the older gltf nodes around for backwards compatibility.
requires: https://github.com/griptape-ai/griptape-vsl-gui/pull/1241
----
📚 Documentation preview 📚: https://griptape-nodes--2012.org.readthedocs.build/en/2012/

update: replace gltf nodes with three_d 

---

pyproject.toml
src/griptape_nodes/app/api.py
src/griptape_nodes/app/app.py
src/griptape_nodes/mcp_server/server.py
tests/workflows/test_workflows.py
uv.lock

This PR decouples the websocket connection from the engine to avoid any low-level connection issues while the engine is working. I'm hoping this will resolve errors like this:
```
ERROR:griptape_nodes_app:Error sending event to Nodes API: received 1011 (internal error) keepalive ping timeout; then sent 1011 (internal error) keepalive ping timeout
```
This is accomplished by spinning up the websocket connection in a daemon thread, and communicating with the engine via `EventManager`'s threadsafe operations.
The engine can send messages back to the websocket by putting messages into an outbound message queue using the threadsafe `loop.call_soon_threadsafe`.

refactor: run websocket connection on separate thread from engine

---

libraries/griptape_nodes_library/griptape_nodes_library/image/save_image.py
src/griptape_nodes/exe_types/node_types.py

Fixes #2106 
Adds the following:
1. Succeeded and Failed control ports
2. A `Status` Parameter group with:
3. `was_successful` <- bool for deciding true/false on success
4. `results_detail` <- forensics for what transpired during save attempt
If we're happy with this, I will systematize the pattern for other save/load and other nodes to reduce the amount of boilerplate necessary.

Added succeeded/failed outputs and advanced Parameter Group for forensics

---

src/griptape_nodes/machines/parallel_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
tests/unit/machines/test_parallel_flow_execution.py

Bug with new parallel in single node resolution - the dag builder doesn't always get properly initialized. This fixes the bug that @aodhanroche was running into where it says "DagBuilder is not initialized" and still fails to cancel the flow.

Fix single node resolution

---

libraries/griptape_nodes_library/griptape_nodes_library/image/save_image.py

If we're happy with this, I have further tasks to systematize this into components that any save or load to make this process easier on the node author.

Removes errant error toasts on Save Image. Allows flows to continue if a failure control path exists instead of canceling the flow.

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/audio/eleven_music_generation.py

Closes #2159 
Adds a new audio node to support the Eleven Music model via the Griptape model proxy.

Add an Eleven Music audio generation node 

---

libraries/griptape_nodes_library/griptape_nodes_library/engine/engine_node.py
src/griptape_nodes/exe_types/node_types.py

Engine Node was the progenitor of SuccessFailureNode, but never got the loving 😿

Migrated EngineNode to SuccessFailure node type

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_memory_footprint.py

In my research, I have discovered that [enable_model_cpu_offload](https://huggingface.co/docs/diffusers/v0.35.1/en/api/pipelines/overview#diffusers.DiffusionPipeline.enable_model_cpu_offload) has superior performance to enable_sequential_cpu_offload
plz ignore revert hell in commit history

Use model CPU offload instead of sequential

---

src/griptape_nodes/exe_types/core_types.py

fixed: #2269
When adding traits (like `Options`) to parameters within a `ParameterGroup`, the trait's ui_options were leaking to all other parameters in the same group. This caused unintended UI elements (like dropdowns) to appear on parameters that didn't have the corresponding traits.
The `Parameter.ui_options` property was inheriting ui_options from its parent `ParameterGroup`:
```python
if self._parent is not None and isinstance(self._parent, ParameterGroup):
parent_ui_options = getattr(self._parent, "ui_options", {})
if isinstance(parent_ui_options, dict):
ui_options = ui_options | parent_ui_options
```
This inheritance mechanism was causing trait-generated ui_options to be shared across all parameters in the same group, even though traits should be parameter-specific.
Removed the …

fix: Prevent ParameterGroup ui_options inheritance from causing trait leakage

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_flux_control_net_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_pro_flux_control_net_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_pro_two_flux_control_net_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_memory_footprint.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/tiling_flux_img_2_img_pipeline.py

For the rollback, we need to ignore pipe_params for the cached function

Fix caching for param changes

---

src/griptape_nodes/cli/commands/models.py
src/griptape_nodes/retained_mode/managers/model_manager.py

Refactors the download model handler to wait for the model download to complete. This way we can convey error details back to the UI. Thanks to the power of async this is ok.
```
[15:46:16] ERROR    Failed to download model 'black-forest-labs/FLUX.1-dev': Downloading model: black-forest-labs/FLUX.1-dev
Model download failed:
401 Client Error. (Request ID: Root=1-68cddd38-517b610204cd4494523332dd;592e71f4-70ea-4816-a6f0-68a475fdb482)
Cannot access gated repo for url
https://huggingface.co/black-forest-labs/FLUX.1-dev/resolve/3de623fc3c33e44ffbe2bad470d0f45bccf2eb21/.gitattributes
.
Access to model black-forest-labs/FLUX.1-dev is restricted. You must have access to it and be authenticated to
access it. Please log
in.
INFO     Completed automatic model downloads: 0 successful, 1 failed
``` …

fix: improve handling during model download failure

---

src/griptape_nodes/exe_types/node_types.py

- Updates to keep `parameter_values` set on a cancellation of the flow, instead of clearing everything in the UI after clearing `parameter_output_values`. 
closes #2217

Fixes Logs clearing on cancel

---

src/griptape_nodes/exe_types/node_types.py

Else users must implement a dummy process. That explains https://github.com/griptape-ai/griptape-nodes/pull/2171#discussion_r2360278625

fix: don't mark process as abstract

---

libraries/griptape_nodes_library/griptape_nodes_library/image/seedream_image_generation.py

This PR updates the Seedream image generation nodes to accept an list of Image artifacts as image inputs, up to ten images in size.

Seedream 4.0: Accept up to 10 input images

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/flux/flux_pipeline_type_flux_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

Turns out we never actually used the provided encoders before, just the defaults (also, you can't set cat to blank, needs to be misc)

Actually use the provided encoders

---

src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Closes #2330 
When a packaged flow gets generated, it generates the workflow shape so that callers know the inputs and outputs necessary.

Packaged flows now have workflow shapes available.

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/image/add_text_to_image.py

Closes #2341 
Very simple, very extensible (yes, we can add fonts, input images for compositing, etc.). But I need something quick that will flex a lot of the scenarios we will be facing.
Pick a background color
Pick a text color
Set the image size
Set the font size
Set the text
Get an image!

A simple Add Text to Image node that will be useful for testing distributed workflows

---

src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/machines/dag_builder.py
src/griptape_nodes/machines/parallel_resolution.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

- adds a GetFlowStateRequest in several different places, so the UI can always be fully up to date on blocked nodes during single node resolution.
- updates tracking of graphs, so nodes can be popped once their graph is completely finished in single node resolution state. node_to_reference should still store the node in it when running a full control flow, this is unique to single node resolution.

Update Events for Proper Flow State tracking in the GUI

---

src/griptape_nodes/app/app.py

Caught by running asyncio in debug mode ([TIL](https://docs.python.org/3/library/asyncio-dev.html)).

fix: initialize app in threadsafe way

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

This is dependent on (built on) https://github.com/griptape-ai/griptape-nodes/pull/2389

Node dependencies (node libraries, imports, files referenced, and workflows referenced) are aggregated when serializing.

---

src/griptape_nodes/retained_mode/managers/library_manager.py

Users found this too magical. Users can still specifiy a directory if they want similar behavior.

refactor!: don't automatically look for libraries in workspace

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

Fixes stubbed toes during publishing/execution.

No longer strips control params on save so that output control flow can be preserved.

---

src/griptape_nodes/cli/commands/engine.py
src/griptape_nodes/cli/main.py

`--no-update` is flag of `gtn engine` not `gtn`. This is confusing.
Closes #2315

refactor: move --no-update from gtn engine to gtn

---

pyproject.toml
src/griptape_nodes/app/watch.py
uv.lock

Removes code, a dependency, and let's us properly ignore `.venv` directories.

refactor: replace watchdog with watchfiles for `make run/watch`

---

src/griptape_nodes/traits/multi_options.py
src/griptape_nodes/traits/options.py

Adds ability for users to search with the Options trait. Default is true. Also provides functionality to pre-fill the trait with the `search_filter` parameter.
fixes: #2213
UI pr: https://github.com/griptape-ai/griptape-vsl-gui/pull/1329

feature: adding search to options trait

---

src/griptape_nodes/exe_types/core_types.py

Adds the ability to add a ButtonTrait to the ParameterMessage, giving it the ability to execute python methods.
https://www.loom.com/share/ad10d3da4b40473aa1b4bc21171ad3d6?sid=884f1704-15d1-444d-a28f-ffb9da8c715f
fixes: #2234
requires: https://github.com/griptape-ai/griptape-vsl-gui/pull/1332

adding button trait to ParameterMessage

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/machines/parallel_resolution.py
src/griptape_nodes/machines/sequential_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/utils/async_utils.py
tests/unit/machines/test_parallel_flow_execution.py

whew, Closes #2376
Nodes cannot be safely cancelled mid-execution. This problem has two aspects, depending on whether nodes implement `def process` or `async def aprocess`.
The asynchronous path is more straightforward since async tasks can be cancelled mid-execution. We create a task from the `aprocess` coroutine and call `task.cancel()`. If the `aprocess` performs purely IO-bound work, the task cancels immediately.
However, complications arise when nodes offload long-running work to threads. When we cancel a task that contains `asyncio.to_thread`, the task appears to complete, but the underlying thread continues running in the background. This is problematic because:
- It creates confusing behavior (the task appears cancelled but isn't truly stopped)
- Background threads continue …

feat: add cooperative cancellation

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_builder_node.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_runtime_node.py

Alternatively could use `griptape_nodes.async_utils.to_thread` but I think this is a better mental model. Doesn't make sense to do CPU bound work in aprocess.
This makes it so that threads don't continue running when cancelled.

fix: use process over aprocess for builder/runtime nodes

---

src/griptape_nodes/drivers/storage/base_storage_driver.py
src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/drivers/storage/local_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

Fixes `\`s appearing in URLs on windows. Yes, I verified on Windows.

fix: convert windows urls to posix when dealing with static files

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/audioldm2/runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/common/upscale_runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/flux/controlnet_runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/flux/img2img_runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/qwen/img2img_runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/qwen/upscale_runtime_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/runtime_parameters.py

Per Amaru this:
1. Moves input image to top of runtime params
1. Provides upscaler and diffuser specific tile params
1. Implements a consistent 20 num_inference_step default

Upscaler param reformat

---

libraries/griptape_nodes_library/griptape_nodes_library/tools/file_manager_tool.py
libraries/griptape_nodes_library/griptape_nodes_library/video/resize_video.py

Fixes #2471
Replace legacy `"hidden": True` pattern with preferred `"hide": True` pattern in `bucket_id` parameter ui_options.
- **File**: `libraries/griptape_nodes_library/griptape_nodes_library/tools/file_manager_tool.py`
- **Line**: 54
- **Change**: `ui_options={"hidden": True}` → `ui_options={"hide": True}`
- Removed TODO comment
- Analysis shows `"hide": True` is used 47 times vs `"hidden": True` used only 3 times
- This standardizes the codebase on the preferred pattern
- ✅ No linter errors
- ✅ Build successful
- ✅ Follows conventional commit format

fix: replace 'hidden' with 'hide' in file_manager_tool.py

---

pyproject.toml
uv.lock

This PR cherry-picks the version bump commit from `release/v0.57`.
Cherry-picked commit: d67e99a67398fb8e44460ef8dca0593f04edafe7

chore: bump v0.57.1

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_builder_node.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_runtime_node.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/managers/node_manager.py

1. Take a snapshot of connections.
2. Remove all parameters.
2a. Now using `RemoveParameterFromNodeRequest` which properly removes connections. 
4. Add back all parameters.
5. Add back all connections.

fix: properly handle connections when removing dynamic connections

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

Also adding this to `on_run_workflow_from_registry_request` so that the editor doesn't kick you to the list workflows screen during boot.
Closes #2530

fix: wait for workflows to finish loading before listing/running them

---

src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/managers/version_compatibility_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Provides the ability to message to the user that nodes in a library are deprecated and may be removed in future versions.
Example Logs:
Example JSON:
```
{
"class_name": "FluxPipeline",
"file_path": "diffusers_nodes_library/pipelines/flux/flux_pipeline.py",
"metadata": {
"category": "image/flux",
"description": "Generate an Image with Flux via 🤗 Diffusers.",
"display_name": "Flux",
"deprecation": {
"is_deprecated": true,
"deprecation_message": "Use 'Diffusion Pipeline Builder' and 'Generate Image (Diffusion Pipeline)' nodes instead.",
"removal_version": "0.59.0"
}
}
},
```

Implement node deprecation flag

---

src/griptape_nodes/common/node_executor.py

* Fall back to Griptape Nodes Library for Start and End Flow Nodes when publishing to a library target in node_executor
Tested with GTC Library

Fall back to Griptape Nodes Library for Start and End Flow Nodes when publishing to a library target in node_executor

---

src/griptape_nodes/retained_mode/managers/secrets_manager.py

Last minute changed `secrets_to_register` to be a nested key in https://github.com/griptape-ai/griptape-nodes/pull/2535. Apparently forgot to test.

fix: use get_config_value to support newly nested nested config key
