griptape-ai/griptape-nodes

README.md
src/griptape_nodes/api/app.py

* Load Nodes API Key correctly

Load Nodes API Key correctly

---

install.ps1
install.sh
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/settings.py

feat: improve install scripts

---

src/griptape_nodes/exe_types/core_types.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/8

refactor: remove validations parameter

---

src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/machines/node_resolution.py

https://www.loom.com/share/ce498806125d44fda1a7ea76b46052d2
Closes #41

feat: add parameter validators/converters

---

src/griptape_nodes/__init__.py

feat(install): add `update` command

---

CONTRIBUTING.md
README.md

Closes #68 
Closes #79
@SavagePencil can you please confirm these documentation updates actually solve the mentioned issues?

docs: update contributing guidelines to cover local dev nuances

---

src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_socket_manager.py
uv.lock

Otherwise commands like `gtn config` may fail due to auth issues.
Also update websocket to pull from config rather than env.

fix: don't initalize socket until after running

---

src/griptape_nodes/api/app.py
src/griptape_nodes/retained_mode/managers/log_manager.py

feat: add startup message telling them to visit website

---

src/griptape_nodes/retained_mode/griptape_nodes.py

re-using variables is bad for your health

Wrong path to library was being echoed; was echo-ing the most recently-loaded node from the library instead of the library path.

---

.vscode/launch.json
src/griptape_nodes/api/app.py

- update launch.json to always point at the venv
- lazier application ready event

Update for less eager application ready event

---

Makefile
pyproject.toml
uv.lock

uv lock during make/version

---

CONTRIBUTING.md
Makefile
nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/agent.py
nodes/griptape_nodes_library/create_image.py
nodes/griptape_nodes_library/drivers/base_image_driver.py
nodes/griptape_nodes_library/drivers/griptape_cloud_image_driver.py
nodes/griptape_nodes_library/drivers/griptape_cloud_prompt_driver.py
nodes/griptape_nodes_library/drivers/openai_chat_prompt_driver.py
nodes/griptape_nodes_library/simple_agent.py
nodes/griptape_nodes_library/tools/prompt_summary_tool.py
nodes/griptape_nodes_library/tools/rag_tool.py
nodes/tests/unit/drivers/test_griptape_cloud_image_generation_driver.py
pyproject.toml
uv.lock

Also update nodes to use Griptape Cloud instead of OpenAi.
Also also add tests to `nodes` package.
Also x 3 fix various type errors that weren't surfaced.
Closes #64

feat: add Griptape Cloud Image Generation Node

---

CONTRIBUTING.md
src/griptape_nodes/retained_mode/managers/log_manager.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/133

Put LogHandlerEvents in event_queue instead of EventBus publish

---

CONTRIBUTING.md
src/griptape_nodes/api/routes/api.py

Layup PR for the UI to specify request id for tracking requests.

fix: pull request_id from paylaod

---

src/griptape_nodes/api/app.py

No longer requires two ctrl-c inputs

fix: properly handle keyboard interrupts

---

install.ps1
install.sh

Closes #148
Are there any better instructions we can provide?

fix: catch if uv is not available during the installation process

---

nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/drivers/audio_transcription_drivers.py
nodes/griptape_nodes_library/drivers/azure_openai_chat_prompt_driver.py
nodes/griptape_nodes_library/drivers/azure_openai_image_driver.py

remove `Base*` node types
fix file references
closes #156

Fix node types in library 

---

src/griptape_nodes/api/app.py
src/griptape_nodes/api/routes/nodes_api_socket_manager.py

don't block requests for heartbeats
Closes #158

Process heartbeat on the listener thread

---

install.ps1
install.sh
src/griptape_nodes/__init__.py

Automatically checks for updates on boot, prompts the user to update.
Closes #147

feat: add auto update

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py

Helps users track down config files in question

feat: add `gtn config list` subcommand

---

src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- Fixed a couple of bugs that @SavagePencil  called out in slack.
- More effectively using user_set_type 
- Actually setting type :sweat_smile:

Fix Type Setting and User Set Type Flag

---

src/griptape_nodes/__init__.py

Write valid json if config file doesnt exist

---

src/griptape_nodes/__init__.py

* Allow specifying the workspace dir as a cli arg on init

Allow specifying the workspace dir as a cli arg on init

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- I do think we should have someee type of type checking, so I added an optional data_type in the setparametervaluerequest for internal use. 
- Thoughts?
closes #202

Remove Errant Type Check

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/os_manager.py

~Untested, needs a windows user.~ Verified, caveat: #214 
Closes #203

fix: support auto update on windows

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Maybe we can use the `_DEBUG` env var in @collindutter 's other PR to set the customer's desired log level?

Shifted almost all logger .info() calls to .debug()

---

docs/reference/glossary.md

----
📚 Documentation preview 📚: https://griptape-nodes--219.org.readthedocs.build//219/

glossary inclusion of some major terms

---

Makefile
src/griptape_nodes/__init__.py

Turns out Github has low rate limits

fix: don't auto-update in debug mode

---

pyproject.toml
uv.lock

Closes https://github.com/griptape-ai/griptape-nodes/issues/227

fix(deps): upgrade griptape to the latest version to resolve tool serialization

---

traits/add_param_button.py
traits/button.py

- Added button modal to test with but introduced a bug.

Quick Fix on agent node

---

.gitignore

gitignore request_payload_schemas.json

---

install.ps1

Closes https://github.com/griptape-ai/griptape-nodes/issues/214

fix(install): fail install on windows if an engine instance is already running

---

nodes/griptape_nodes_library/agents/base_agent.py
nodes/griptape_nodes_library/agents/create_agent.py

https://www.loom.com/share/dc2d7e8680914cbd9df43ca8760579dc?sid=6c8da287-8653-46a9-b63e-3771bdb69767

updated base_agent to include prompt_context

---

nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/dict/display_dict.py
nodes/griptape_nodes_library/dict/merge_key_value_pair.py
nodes/griptape_nodes_library/number/__init__.py
nodes/griptape_nodes_library/number/create_float.py
nodes/griptape_nodes_library/number/create_int.py
nodes/griptape_nodes_library/number/display_float.py
nodes/griptape_nodes_library/number/display_int.py
nodes/griptape_nodes_library/text/display_text.py

added display text, dictionary, float, int nodes
added create integer and create float nodes

Created display nodes for text, dict, float, int

---

.vscode/launch.json

Technically the correct fix is to rebase onto main but it's annoying

fix: disable auto update when debugging

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/payload_registry.py
src/griptape_nodes/traits/trait_registry.py

Reverts discussion here: https://github.com/griptape-ai/griptape-nodes/pull/244#discussion_r2033601642

revert: don't use instance fields for registries

---

src/griptape_nodes/__init__.py

feat: add uninstall command

---

pyproject.toml
src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/retained_mode.py

Tracebacks are too noisy in most scenarios

refactor: intentionally use errors in scenarios where we safely handle it

---

nodes/griptape_nodes_library/image/describe_image.py

Tested with connecting agents, and also using different prompt drivers on those agents.

ensured the PromptTask uses GriptapeCloudPromptDriver if none is supplied.

---

src/griptape_nodes/retained_mode/managers/operation_manager.py

Reduce long set_parameter_value echoes back to the editor.

---

nodes/griptape_nodes_library/utils/reroute.py

Closes #198 
Added #364 to complete the fix.

Makes the rerouter not crash. Currently limited as it requires someone to connect to its input FIRST before an output can be connected.

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Passing exception details back on failures. Is this enough?

---

docs/how_to/making_custom_nodes.md
docs/how_to/making_custom_scripts.md
mkdocs.yml

related to
https://github.com/griptape-ai/griptape-nodes/issues/341
----
📚 Documentation preview 📚: https://griptape-nodes--378.org.readthedocs.build//378/

making custom X

---

CONTRIBUTING.md
src/griptape_nodes/exe_types/core_types.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/403

docs: update contributing install command

---

src/griptape_nodes/__init__.py
src/griptape_nodes/exe_types/core_types.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/398

fix: add more checks to uninstaller to catch edge-cases

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- added some new functionality both in the node and with requests to delete children of deleted groups and lists. 
- closes #388 and closes #387

Delete ParameterLists and ParameterGroups

---

src/griptape_nodes/__init__.py

feat: open browser automatically when starting engine

---

src/griptape_nodes/retained_mode/managers/operation_manager.py

- UI options are now a dictionary 
- Needed to be simplified
- Unblocks @aodhanroche for display

Update for ui_options now being a dictionary

---

src/griptape_nodes/retained_mode/managers/config_manager.py

Fixes regression introduced by https://github.com/griptape-ai/griptape-nodes/pull/409
Closes #420

fix: merge delta config with existing config on disk

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/settings.py

Had to revert #419 because of demo. Adds that back and includes a fix `extra="allow"`.

fix: consider config files in workspace directory (#419)

---

install.ps1
install.sh

Updates the install scripts to install from the release tarball rather than git.
Closes #371

feat: install without git

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Closes #429 
Previously would not return an error message. Now we get something akin to:
```
Attempted to load Library JSON file from 'nodes/griptape_nodes_library.json'. Failed due to an error loading node GenerateImage: Class 'GenerateImage' from module '/Users/<your name here>/Projects/griptape-nodes/nodes/griptape_nodes_library/image/create_image.py' failed to load with error: unterminated string literal (detected at line 20) (create_image.py, line 20)
```

We weren't try/catching around the module exec during library load. Now catching that and giving more explicit instruction.

---

src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

- allows the editor to get the current canvas when switching between tabs/sessions

Adding GetTopLevelFlowRequest

---

src/griptape_nodes/__init__.py

Taking the other, less annoying, path on #373

refactor: only open browser window on first init

---

src/griptape_nodes/__init__.py

Behavior changed in
https://github.com/griptape-ai/griptape-nodes/pull/438
Closes #447

fix: update workspace prompt to reflect new settings

---

src/griptape_nodes/retained_mode/griptape_nodes.py

Echo the workflow path on successful save.

---

src/griptape_nodes/__init__.py

refactor: remove api key logging

---

src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/context_manager.py

Create a context manager that can maintain the current state of what is current and what is pushed for Flows and Nodes

---

pyproject.toml
uv.lock

https://github.com/griptape-ai/griptape-nodes/issues/475

deps: remove explicit marshmallow pin in favor of bumped griptape

---

src/griptape_nodes/app/app.py

Engine running text color fix

---

src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/events/app_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Changes required for https://github.com/griptape-ai/griptape-vsl-gui/pull/431

Improve/Fix App Events

---

nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/image/load_image.py
nodes/griptape_nodes_library/image/save_image.py
nodes/griptape_nodes_library/utils/image_utils.py

Made a **SaveImage** node, added it to the library, pulled **dict_to_image_artifact** out of **LoadImage** and created an **image_utils** file that both Load and Save pull from.
Closes #317

Save Image node

---

src/griptape_nodes/app/app.py
src/griptape_nodes/machines/node_resolution.py

Changes discussed on call with @kateforsberg13. Supports https://github.com/griptape-ai/griptape-vsl-gui/pull/451

Various Event Fixes

---

workflows/templates/prompt_an_image.py

It's still not loading any nodes for me but that may be a personal issue. This at least solves the initial load.
(maybe closes) #485

fix: use correct name for workflow

---

nodes/griptape_nodes_library/drivers/prompt/ollama_prompt_driver.py
src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/traits/options.py

When creating a Trait inside a Parameter Group it first receives the Parameter Group as its parent. Then it is updated to the actual element.
Closes #519

Traits Fixes

---

.github/ISSUE_TEMPLATE/bug_report.yml

It's [REPORT] and Collin will yell at us (UPDATE: yelling will now be _opt-in_ for Collin)

---

install.ps1
install.sh
src/griptape_nodes/__init__.py

Moves much of the install/update process from shell script to python.
Closes #561
Closes #554
Closes #214

refactor: improve install process

---

src/griptape_nodes/exe_types/flow.py

refactor: improve error messages

---

nodes/griptape_nodes_library/image/describe_image.py

feat: run describe image in background

---

nodes/griptape_nodes_library/utils/end_flow.py
nodes/griptape_nodes_library/utils/start_flow.py

temporarily adding input and output parameters for start and end flows

adding temporary input and output parameters

---

src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

UI needs to listen for cancellations: https://github.com/griptape-ai/griptape-vsl-gui/pull/472

feat: add ControlFlowCancelledEvent

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/config_manager.py

feat: add `gtn config reset` command

---

nodes/griptape_nodes_library/drivers/web_search/web_search_drivers.py
nodes/griptape_nodes_library/tools/web_search_tool.py
pyproject.toml
uv.lock

duckduckgo pyproject uvlock and non-dict updates (#585)

---

nodes/griptape_nodes_library/image/create_image.py

Pared-down change to GenerateImage: enhance_prompt default False

enhance_prompt defaults False

---

src/griptape_nodes/machines/node_resolution.py

refactor: make pausing message a debug log

---

src/griptape_nodes/exe_types/node_types.py

closes #537 
Ruleset node was not being evaluated! Now it is. 
One line fix

Ruleset node not properly evaluating

---

nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/image/display_image.py

display image node

---

src/griptape_nodes/__init__.py

fix: install workflows/scripts on fresh install

---

src/griptape_nodes/__init__.py

Fixes issues when restarting the executable after an update has occurred. I started with this implementation but went in a different direction because of errors that I believe were unrelated. Verified this works on mac/windows.

fix: improve auto-restart

---

src/griptape_nodes/machines/control_flow.py

- This is similar to the flow execution fix that we had previously. Now we're checking for the next nodes in the flow queue in just another place where without a control flow it can still resolve the next node. 
closes #590 
There are some weird UI bugs going on with this flow however - it's receiving the correct ParameterUpdateValueEvents, but every once in a while it resets everything to be a different value. it fixes itself on refresh.

Fix flow resolution with Data Nodes

---

src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py

When a node is deleted while the flow is running, it cancels the whole flow.
closes #633 
This only happens if you delete a node that is connected to the nodes that are currently executing!

Deleting a node Kills a flow 

---

src/griptape_nodes/retained_mode/managers/event_manager.py

- Seems like everything is serialized before it gets to this point, because it never hits the inside of the if statement.

Removing Extra Serialization

---

CONTRIBUTING.md
src/griptape_nodes/app/app.py

fix: automatically use an OS-provided free port

---

src/griptape_nodes/app/app.py

feat: add rich handler to uvicorn

---

nodes/griptape_nodes_library/image/create_image.py
nodes/griptape_nodes_library/image/describe_image.py
nodes/griptape_nodes_library/image/display_image.py
nodes/griptape_nodes_library/image/load_image.py
nodes/griptape_nodes_library/image/save_image.py

fix: add support for ImageUrlArtifact to image nodes

---

src/griptape_nodes/__init__.py

Doing so puts us in a really weird state. Until we can find a proper solution (don't know if one exists), we should just avoid doing this at all. Worse case scenario the user has a stray `gtn` executable on their system that they can clean up manually by following our instructions.
Closes #604

refactor: don't attempt self uninstallation on Windows

---

nodes/griptape_nodes_library/image/create_image.py

Change validation to be runtime only, not on set value.

---

pyproject.toml
src/griptape_nodes/app/app.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/retained_mode/griptape_nodes.py

Long term we may want to consider creating our own exception, but this is at least consistent with other places in the codebase.

refactor: don't ignore TRY002

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Add event imports to saved workflow files
Closes #706

Add event imports to saved workflow files

---

src/griptape_nodes/exe_types/flow.py

fix: cancel flow run if error starting it

---

nodes/griptape_nodes_library/image/create_image.py

Closes #707 
s'dumb that a Node can't ask for it's connections, so we have that in #720

Don't abort validation if we have a connection to the prompt parameter.

---

src/griptape_nodes/app/nodes_api_socket_manager.py

Adds a debug log for a heartbeat request response indicating session and request IDs.

Debug log for heartbeat

---

src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Fix script imports
* Fix circular dep

Fix script imports. Fix circular dep.

---

nodes/griptape_nodes_library.json
nodes/griptape_nodes_library/image/compare_images.py
src/griptape_nodes/traits/compare_images.py

Compare Images Node. Can test with this with `main`

Compare Image Node

---

uv.lock

fix: update griptape version to support serializing structure run tool

---

nodes/griptape_nodes_library/image/compare_images.py

Fixed parameter name with spaces, but more issues on the horizon

---

src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Make workflow and library tables consistent, echo enumstr.

---

nodes/griptape_nodes_library/agents/agent.py
nodes/griptape_nodes_library/image/create_image.py
workflows/templates/compare_prompts.py
workflows/templates/photography_team.py

This should be an actual value, streamed values are appended to it

refactor: make "Node hasn't begun yet" text placeholder text

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py

feat: add cycle detection

---

nodes/griptape_nodes_library/image/load_image.py
nodes/griptape_nodes_library/image/save_image.py
nodes/griptape_nodes_library/utils/image_utils.py

refactor: make load/save image operate on image url artifacts

---

src/griptape_nodes/retained_mode/managers/flow_manager.py

Fixes corner case from https://github.com/griptape-ai/griptape-nodes/pull/783
Closes #793

fix: safely cancel flow run rather than taking the whole engine down

---

src/griptape_nodes/__init__.py

feat: install assets during auto update

---

CONTRIBUTING.md
nodes/griptape_nodes_library.json
nodes/griptape_nodes_library_extras.json
src/griptape_nodes/retained_mode/managers/settings.py

I took the shortest path ... and I like it.

Add second default library for "extras"

---

nodes/griptape_nodes_library/image/compare_images.py
src/griptape_nodes/traits/compare_images.py

[Corresponding Editor PR](https://github.com/griptape-ai/griptape-vsl-gui/pull/563)

Fix the Compare Image Node/Trait 

---

docs/faq.md

----
📚 Documentation preview 📚: https://griptape-nodes--815.org.readthedocs.build/en/815/

add Settings > Copy Path to Settings to FAQ

---

docs/reference/command_line_interface.md
mkdocs.yml

Looking forward to more detail on https://github.com/griptape-ai/griptape-nodes/issues/677 to know if I've addressed it or not
----
📚 Documentation preview 📚: https://griptape-nodes--812.org.readthedocs.build/en/812/

Made a CLI Page

---

docs/reference/glossary.md

----
📚 Documentation preview 📚: https://griptape-nodes--811.org.readthedocs.build/en/811/

Add port and pin to the glossary

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Fixes #801 
Some notes:
1. Legacy workflows will need to be re-saved in order to get the creation and modified date.
2. If not found, the system will default to Jan 1, 1970. This will keep old files at the bottom of the list.

Including creation and last modified time into workflow metadata.

---

nodes/diffusers_nodes_library/tiling_flux_img_2_img_pipeline.py
nodes/diffusers_nodes_library/utils/math_utils.py
nodes/diffusers_nodes_library/utils/tiling_image_processor.py
nodes/pillow_nodes_library/utils.py
nodes/spandrel_nodes_library/tiling_span.py
nodes/spandrel_nodes_library/utils.py

And fix tiling sizes, actually required for removing the scaling parameters due to the implications.

Remove scale parameters from Tiling* nodes

---

docs/faq.md

----
📚 Documentation preview 📚: https://griptape-nodes--822.org.readthedocs.build/en/822/

Added CLI version to path query

---

src/griptape_nodes/retained_mode/events/base_events.py

The current default of `str` was causing some objects to be transformed into their most basic string form. This adds a bit more intelligence to handle griptape serializable objects and pydantic models.

fix: improve fallback json encoding of events

---

src/griptape_nodes/retained_mode/managers/config_manager.py

Somehow @griptapeOsipa ended up with a bad config. Now we more gracefully handle that scenario.
Closes #809

fix: catch bad configs when adding values

---

install.ps1
install.sh

Closes #901
Closes #900
Closes #899
Closes #884

feat: install from pypi rather than git

---

src/griptape_nodes/__init__.py
src/griptape_nodes/updater/__init__.py

Use `os.execvp` rather than creating subprocesses.

Fix Auto Restart

---

nodes/diffusers_nodes_library/tiling_flux_img_2_img_pipeline.py
nodes/diffusers_nodes_library/utils/tiling_image_processor.py
nodes/spandrel_nodes_library/tiling_span.py

Resolves https://github.com/griptape-ai/griptape-nodes/issues/790
Resolves https://github.com/griptape-ai/griptape-nodes/issues/879
Resolves https://github.com/griptape-ai/griptape-nodes/issues/851

Add partial tile previews

---

install.ps1
install.sh

Need to test more on windows.
Closes #882

fix: don't rely on PATH during uv installation

---

install.ps1
install.sh

fix: don't show stdout from 3p installers

---

docs/faq.md
src/griptape_nodes/__init__.py

New way of uninstallation that should work on Windows. ~Need to test on Windows~worx

fix: switch process before uninstalling self

---

src/griptape_nodes/__init__.py
src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/managers/config_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

feat: prompt user on whether they'd like to register library extras

---

docs/ftue/01_prompt_an_image/FTUE_01_prompt_an_image.md
docs/ftue/02_coordinating_agents/FTUE_02_coordinating_agents.md
docs/ftue/03_compare_prompts/FTUE_03_compare_prompts.md
docs/ftue/04_photography_team/FTUE_04_photography_team.md
docs/ftue/FTUE.md

----
📚 Documentation preview 📚: https://griptape-nodes--961.org.readthedocs.build/en/961/

prepend "lesson #:"  through FTUE titles

---

install.ps1
install.sh
pyproject.toml
uv.lock

This allows us to live on pypi ourselves

refactor: use pypi version of griptape

---

src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Solves the issue of new griptape workflows not appearing. Related to #970

feat: support registering all workflows in a directory

---

install.ps1
install.sh

May resolve path issues during first time install

fix: update shell during installation

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/retained_mode/managers/library_manager.py

The schema wasn't handling dependencies correctly. Updated the schema code and the advanced media library .json.

Fixed the broken schema and the broken implementation of the schema [NEEDS A NEW RELEASE]

---

src/griptape_nodes/exe_types/connections.py
src/griptape_nodes/exe_types/flow.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/machines/control_flow.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Closes #819 
I feel unwashed by this so I made https://github.com/griptape-ai/griptape-nodes/issues/994 for FUTURE US.

Go through a make_unresolved call wherever possible in order to broadcast to GUI

---

workflows/templates/photography_team.py

- changing prompt to be about a skateboarding lion
- Added decency clauses to the prompt rules

last swing before weighing preview cut

---

install.ps1
src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/updater/__init__.py

fix: bunch of windows installation/update hacks

---

src/griptape_nodes/__init__.py
src/griptape_nodes/updater/__init__.py

Causes way too many problems. Removing for now. Maybe dedicated installer in the future.

refactor: remove auto restart after update

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py

Added this to the last line of prompt guidance:
IMPORTANT: Always ensure image generation prompts are completely free of sexual, violent, hateful, or politically divisive content. When in doubt, err on the side of caution and choose wholesome, neutral themes that would be appropriate for all audiences.

added safety guidance to enhance_prompt

---

src/griptape_nodes/exe_types/core_types.py
src/griptape_nodes/retained_mode/griptape_nodes.py

closes #685 
Saves updates made to ParameterGroups in addition to normal Parameters. 
This prevents the groups from being hidden on reopening a saved file.

Fix UI options being overwritten

---

src/griptape_nodes/retained_mode/managers/arbitrary_code_exec_manager.py

fix: strip ansi escape characters in response

---

src/griptape_nodes/updater/__init__.py

chore: add message after update

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/griptape_nodes_library/config/image/griptape_cloud_image_driver.py
libraries/griptape_nodes_library/griptape_nodes_library/config/image/openai_image_driver.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/amazon_bedrock_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/anthropic_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/cohere_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/griptape_cloud_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/grok_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/openai_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py
libraries/griptape_nodes_library/griptape_nodes_library/tools/audio_transcription_tool.py
libraries/griptape_nodes_library/griptape_nodes_library/tools/extraction_tool.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py

Refactor Node Verification

---

src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Fixes #1024 
After status is reported for libraries and workflows, check for any missing files and remove them from their respective registries.

Workflows and Libraries that are missing are removed from the registries

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py

check da set before ya wreck da flow

Only remove from a set when you know it's in there :taps head sagely:

---

libraries/griptape_nodes_library/griptape_nodes_library.json
src/griptape_nodes/node_library/library_registry.py

Confirm if this addresses issue 656 in GUI

Put default libraries first in the list. Honor the is_default_library flag in library.JSON

---

src/griptape_nodes/__init__.py

Adds auto updating from git installs on 'latest' tag. This is how we (griptape) should install and update.
Closes #918 
Related #1065

feat: change auto-update logic based on install source

---

src/griptape_nodes/retained_mode/managers/config_manager.py

Mirrors behavior in `get_config_value` that retrieves secrets starting with `$`. This has a nice side effect of secrets registered by a library now appear when the library is loaded rather requiring an engine restart.
Closes #1022

feat: set empty secret value when setting config value starting with $

---

src/griptape_nodes/__init__.py

[I lied](https://github.com/griptape-ai/griptape-nodes/pull/1065#issuecomment-2860591203). This ensures that nightly users are pulling assets from the latest and greatest.

fix: download assets from 'latest' tag unless installed from stable pypi

---

src/griptape_nodes/retained_mode/managers/event_manager.py

closes #661 
Requires a request ID for retained mode to be echoed. 
Tied to https://github.com/griptape-ai/griptape-vsl-gui/pull/700

Prevents extraneous retained mode commands

---

.github/workflows/latest-release.yml
.github/workflows/latest-tag.yml
.github/workflows/stable-release.yml

Actions for creating releases now look the same. New action for creating tag.

ci: clean up release actions

---

pyproject.toml
uv.lock

deps: update griptape

---

src/griptape_nodes/__init__.py

__get_install_source returns a tuple, need to unpack that

fix: properly parse install_source when syncing assets

---

.github/workflows/latest-tag.yml

Latest tag was being created but not the new release

ci: use PAT token so that workflows can trigger other workflows

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/audio/__init__.py
libraries/griptape_nodes_library/griptape_nodes_library/audio/audio_url_artifact.py
libraries/griptape_nodes_library/griptape_nodes_library/audio/library_style.json
libraries/griptape_nodes_library/griptape_nodes_library/audio/load_audio.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/audio_utils.py

* Add LoadAudio Node
https://www.loom.com/share/e022b401f62a403c8d3ae9133287f3eb?sid=f5e717c5-6c0f-4021-bcdd-2d395d86a18a
Related GUI [PR](https://github.com/griptape-ai/griptape-vsl-gui/pull/714)

Add LoadAudio Node

---

docs/faq.md

----
📚 Documentation preview 📚: https://griptape-nodes--1113.org.readthedocs.build/en/1113/

AVM install added to FAQ

---

docs/nodes/config/anthropic_prompt_driver.md
docs/nodes/config/cohere_prompt_driver.md
docs/nodes/config/griptape_cloud_image_driver.md
docs/nodes/config/griptape_cloud_prompt_driver.md
docs/nodes/config/grok_image_driver.md
docs/nodes/config/openai_image_driver.md
docs/nodes/config/openai_prompt_driver.md

----
📚 Documentation preview 📚: https://griptape-nodes--1112.org.readthedocs.build/en/1112/

param alignment updates

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/execution/if_else.py
libraries/griptape_nodes_library/griptape_nodes_library/execution/select_output.py

Adds the If else and the output selector node to the node library.

If Else and Output Selector Node

---

libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/griptape_cloud_prompt.py

feat: call list models to get all available cloud chat prompt models

---

src/griptape_nodes/__init__.py

Adds a line explaining what customers can do with the advanced media library.

Explain what advanced lib affords.

---

src/griptape_nodes/app/app.py

Adds the nodes-staging domain to the CORS config.

Update CORS config to allow for staging editor domain

---

docs/faq.md

----
📚 Documentation preview 📚: https://griptape-nodes--1163.org.readthedocs.build/en/1163/

Added FAQ for SSL self cert issue

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/execution/compare_numbers.py

Quick feature for a compare numbers node.

adds a Compare Numbers node

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/execution/compare_strings.py

feature: compare strings node

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/image/webcam.py

Dependent on pending editor PR and subsequent deployment.

Add webcam node

---

src/griptape_nodes/exe_types/type_validator.py
src/griptape_nodes/node_library/library_registry.py
src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/payload_registry.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/traits/trait_registry.py
src/griptape_nodes/utils/metaclasses.py

Round 2. Verified that the engine boots up this time.
This reverts commit 1cf5518e31ccc71c7784a897cba794a0ce616f6f.

Reapply "refactor: remove reliance on griptape's SingletonMixin (#1174)"

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

1189 make serialized saving the default

---

libraries/griptape_nodes_library/griptape_nodes_library/tools/web_search_tool.py

fixed websearch tool

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/river_z_normal_diptych_flux_fill_lora.py
libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

https://griptape-ai.slack.com/archives/C0876P576SG/p1747322399674209
https://griptape-ai.slack.com/archives/C0876P576SG/p1747327496665109

Add flux fill and diptych flux fill pipelines

---

src/griptape_nodes/__init__.py

This keeps coming up in rehearsals. I propose we get rid of the tab opening

Don't open a tab when starting the engine

---

libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py

add output to the image parameter

---

Makefile
pyproject.toml

[WIP] 
updating pyproject.toml and makefile

Exclude Workflows from checks

---

libraries/griptape_nodes_advanced_media_library/controlnet_aux_nodes_library/anyline_detector.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/file_path_parameter.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_model_parameter.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/flux_control_net_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_one_flux_control_net_model.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_two_flux_control_net_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_loras_parameter.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/tiling_flux_img_2_img_pipeline.py
libraries/griptape_nodes_advanced_media_library/opencv_nodes_library/canny_convert_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/gaussian_blur_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/grayscale_convert_image.py
libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/rescale_image.py
libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/tiling_span.py
libraries/griptape_nodes_advanced_media_library/transformers_nodes_library/depth_anything_for_depth_estimation.py

Add output pins to all inputs in advanced media nodes

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_from_file.py

Fix Path in lora dict key

---

src/griptape_nodes/retained_mode/managers/node_manager.py

closes #1204 
Saves all values on the parameter- input and output. 
Stores/saves them in the same way as previously.

Save Parameter Values and Output Values

---

Makefile
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_parameters.py

Add text encoder model names to flux pipeline nodes

---

pyproject.toml

[Defaults here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md)
Thank you @vachillo 
[based on this comment](https://github.com/griptape-ai/griptape-nodes/pull/1227#issuecomment-2887599689)

Add back in pyright defaults

---

docs/faq.md

Closes #1089 
----
📚 Documentation preview 📚: https://griptape-nodes--1240.org.readthedocs.build/en/1240/

docs: add FAQ for installing pre-release builds

---

src/griptape_nodes/retained_mode/managers/config_manager.py

fix: preserve workflows_to_register when resetting config

---

libraries/griptape_nodes_library/griptape_nodes_library.json

added microphone node

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py

disable ParameterMode.PROPERTY

---

src/griptape_nodes/retained_mode/managers/node_manager.py

`node_name` was still the 'copied' node's name, which was causing errors and weirdness on paste. 
Initially, I removed `node_name` altogether and was having `AddParameterToNodeRequest` and `AlterParameterRequest` use context, but that was causing an error with `GetAllNodeInfoRequest` where it didn't have a `node_name` provided and there was no node in the context. So now I am manually setting `node_name`.

Fixing Serialization Error 

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/error_utils.py

Workaround until https://github.com/griptape-ai/griptape/issues/1946 is implemented and propagated to Cloud.
Closes #972

feat: properly parse and present image generation errors

---

src/griptape_nodes/__init__.py

Also don't show explainer when using CLI args.

fix: properly respect workspace-directory passed as CLI args

---

Makefile

Else we may have stale local tags

fix: fetch tags before publishing new ones

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Merge workspace env with SecretsManager values for published workflow env
* We can gather all secrets explicitly defined in the workspace .env file, and by the settings/SecretsManager, but we will not gather all secrets from the OS env for the purpose of publishing
* Prefer workspace env values over SecretsManager values, to follow the [preference of the SecretsManager class itself](https://github.com/griptape-ai/griptape-nodes/blob/main/src/griptape_nodes/retained_mode/managers/secrets_manager.py#L106-L110)
Closes #1261

Merge workspace env with SecretsManager values for published workflow env

---

src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/node_manager.py

- updates event to take position
- returns node names for paste so the editor knows which nodes to select.

Paste to Mouse Position

---

CONTRIBUTING.md

update CONTRIBUTING.md to clarify docs contribution workflow

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_loras_parameter.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_from_file.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_parameters.py

Fix loras type and add trigger phrase to lora file

---

CONTRIBUTING.md

docs: update contributing guidelines for docs

---

src/griptape_nodes/retained_mode/managers/node_manager.py

Using `deepcopy` instead produces the same (if not better) behavior, and prevents the errors being thrown on `.copy()` with strings and other objects. 
closes #1258 
While working, I discovered metadata wasn't being copied on node recreation after multiple pastes in a row, so I also updated that, which closes #1323 . (Or at least solves one of the problems we were having of nodes stacking).

Get Rid of Serialization Warning

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

Edit advanced media display names and descriptions

---

src/griptape_nodes/retained_mode/managers/library_manager.py

I tested it on windows. it works now

Fix emojis in library json on windows

---

src/griptape_nodes/machines/node_resolution.py
src/griptape_nodes/retained_mode/events/execution_events.py
src/griptape_nodes/retained_mode/events/node_events.py
src/griptape_nodes/retained_mode/managers/node_manager.py

CreateNode Node Type and Library for Analytics

---

libraries/griptape_nodes_library/griptape_nodes_library/dict/merge_key_value_pair.py

added PROPERTY

---

libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/griptape_cloud_prompt.py

Temporarily restricts the available models in GriptapeCloudPromptDriver to ones that are currently working.

update: GriptapeCloudPromptDriver model list

---

libraries/griptape_nodes_library/griptape_nodes_library/dict/key_value_pair.py

Update: add ability to pass key/value inputs to KeyValuePair node

---

libraries/griptape_nodes_library/griptape_nodes_library/image/paint_mask.py

fixed #1386
requires: https://github.com/griptape-ai/griptape-vsl-gui/pull/866

fix: paint_mask outputs working mask

---

docs/nodes/config/groq_prompt_driver.md
libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/groq_prompt.py
mkdocs.yml

----
📚 Documentation preview 📚: https://griptape-nodes--1401.org.readthedocs.build/en/1401/

Feature: Groq Prompt Driver

---

src/griptape_nodes/__init__.py

Useful for headless environments that need to set a couple values without being prompted for everything else. 
Also adds init arguments for --storage-backend and --storage-backend-bucket-id.
Also refactors all of the `_prompt_for_x` to only do the prompting. Their responsibilities were a bit overloaded.
Sorry for messy PR diff.

feat: add --no-interactive flag to gtn init

---

src/griptape_nodes/retained_mode/managers/config_manager.py

update: set on_handle_get_config_category_request to debug

---

src/griptape_nodes/retained_mode/events/agent_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/agent_manager.py

Introduces Run Agent, Get Conversation Memory, and Reset Agent.

Basic events for chat Agents

---

.github/workflows/publish.yml
Dockerfile

* Update Dockerfile to support gpu

Update Dockerfile to support gpu

---

src/griptape_nodes/retained_mode/managers/library_manager.py

Fixes issues when installing using a requirements specifier in docker environment.

fix: install requirement specifier libraries in venvs directory

---

src/griptape_nodes/app/__init__.py

Once we've proven this is stable in prod i'll remove dead code

feat: enable websockets by default

---

CLAUDE.md

Adding claude code auto-gen CLAUDE.md. Can probably be improved.

Adding Claude Code auto-gen CLAUDE.md. Gives context for Claude copilot working with Griptape Nodes.

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/seed_parameter.py

publish apparently updates the ui, but not the actual value, so randomize seed looked like it was working when it wasn't. You need to call set_parameter_value whenever you call publish_update_to_parameter

Fix randomize seed

---

src/griptape_nodes/retained_mode/managers/library_manager.py

By placing a library's venv next to its config file, we can leverage existing venvs (like on a shared drive :eyes:)

feat: install library deps relative to install location

---

.gitignore
.vscode/settings.json
.vscode/tasks.json
CLAUDE.md
pyproject.toml
uv.lock

Closes #1488 
Documentation to come in #1489

Add profiling as an extra. Adds VSCode tasks to facilitate profiling from within the IDE.

---

src/griptape_nodes/__init__.py
src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

Also works in non-interactive mode.
`GTN_STORAGE_BACKEND=gtc GTN_BUCKET_NAME='foo' uv run gtn init --no-interactive`
Closes #1503
Closes #1332

feat: add ability to specify/auto-create buckets

---

src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py

fix: respect static files directory in gtc storage driver

---

src/griptape_nodes/__init__.py

Progress towards https://github.com/griptape-ai/griptape-vsl-api/issues/64

feat: add ability to specify libraries base dir

---

src/griptape_nodes/retained_mode/managers/node_manager.py

fix: generates a unique parameter name

---

src/griptape_nodes/retained_mode/events/parameter_events.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/operation_manager.py

fixes: #1528
required for: #1525

feature: added ability to rename a parameter

---

src/griptape_nodes/__init__.py

Allows users to change where libraries are synced to (like a shared drive):
```bash
GTN_LIBRARIES_BASE_DIR=~/Desktop/libraries uv run gtn libraries sync
```
And how engines are init-ed:
```bash
GTN_LIBRARIES_BASE_DIR=~/Desktop/libraries uv run gtn init
```

feat: support GTN_LIBRARIES_BASE_DIR during library sync

---

libraries/griptape_nodes_advanced_media_library/dino_sam2_library/__init__.py
libraries/griptape_nodes_advanced_media_library/dino_sam2_library/dino_sam_2_detector_parameters.py
libraries/griptape_nodes_advanced_media_library/dino_sam2_library/dino_sam_2_image_detector.py
libraries/griptape_nodes_advanced_media_library/dino_sam2_library/dino_sam_2_video_detector.py
libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

resolves #1357  
resolves #1539

Add text to image and video mask nodes

---

src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Eliminate spurious workflow warning, eliminate legacy workflows/templates/ dir as being included in default workflows to load

---

docs/nodes/video/resize_video.md
libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/video/resize_video.py
mkdocs.yml
pyproject.toml
uv.lock

https://www.loom.com/share/64a392dca77b40888a4ebd156c6d946a?sid=dbbd47e2-602f-403b-b4ae-b10ac3e62593
fixes: #1574
fixes: #1575
----
📚 Documentation preview 📚: https://griptape-nodes--1576.org.readthedocs.build/en/1576/

feature: added resize_video node

---

src/griptape_nodes/version_compatibility/versions/v0_39_0/modified_parameters_set_removal.py

- Adds ui_options warning in addition to modified parameters set warning.

Updating Library Version Message

---

src/griptape_nodes/app/app.py

fix: load GT_CLOUD_API_KEY using secrets manager

---

src/griptape_nodes/retained_mode/events/agent_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/agent_manager.py

Text2Image
Image2Text
Streaming
Threaded Agent
https://www.loom.com/share/213ab614424545d7a4e371dd447548ba?sid=575f6f27-f64f-419a-8134-e5d58115730f

Support passing artifacts on RunAgentRequest

---

src/griptape_nodes/__init__.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Fix issue with saving enum class to workflow

Fix issue with saving enum class to workflow

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/workflows/templates/photography_team.py

fixes: #1621
updates the photography team template to work with new ParameterLists

fix: agent tools and rules can take lists again

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

* Fix workflow shape logs
* Remove the right log statements this time

Fix workflow shape logs

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/__init__.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/huggingface_repo_file_parameter.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/model/__init__.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/model/body.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/model/hand.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/model/model.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/model/util.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/openpose_image_detection.py
libraries/griptape_nodes_advanced_media_library/openpose_nodes_library/openpose_video_detection.py

Images:
Videos:
resolves #1537

Add openpose

---

src/griptape_nodes/retained_mode/events/workflow_events.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

New save event version that allows replacing the thumbnail image of a workflow
[Partner PR](https://github.com/griptape-ai/griptape-vsl-gui/pull/982)

Event to replace thumbnail image on save

---

libraries/griptape_nodes_library/griptape_nodes_library/image/compare_images.py
src/griptape_nodes/traits/compare_images.py

Special Kyroquest
[Partner PR](https://github.com/griptape-ai/griptape-vsl-gui/pull/981)
Rename to A & B

Compare images node update

---

libraries/griptape_nodes_library/griptape_nodes_library/image/compare_images.py
src/griptape_nodes/traits/compare_images.py

Reverts griptape-ai/griptape-nodes#1634

Revert "Compare images node update"

---

src/griptape_nodes/app/__init__.py
src/griptape_nodes/app/app.py
src/griptape_nodes/app/app_sessions.py
src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/events/library_events.py
src/griptape_nodes/retained_mode/events/workflow_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/event_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/managers/settings.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Now checks disk space before attempting potentially large disk write operations. These values are settable within the Engine Settings section of the Configuration.

Verify adequate disk space availability before key operations (dependency install, workflow saving). User-adjustable setting.

---

src/griptape_nodes/retained_mode/managers/secrets_manager.py

feat: load secrets into environment variables (non-overriding)

---

src/griptape_nodes/retained_mode/managers/event_manager.py

- Lingering app.app import that needed to be moved to app.sessions!

Fix the dynamic parameter updates

---

libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py

gpt-image-1 was previously incorrectly missed from this model list

Add gpt-image-1 as model option for GTC image gen

---

CLAUDE.md

This is sent up with every claude request so it's important that we keep it relatively lean with information that will directly help claude. This PR removes some context that is not relevant to day-to-day engine development.

docs: update CLAUDE.md

---

src/griptape_nodes/app/api.py
src/griptape_nodes/app/app.py
src/griptape_nodes/bootstrap/workflow_runners/subprocess_workflow_runner.py
src/griptape_nodes/drivers/storage/local_storage_driver.py

This was getting unweildly to maintain in one file.

refactor: move fastapi server to dedicated module

---

src/griptape_nodes/app/api.py

Continuation of #1715. Was hitting function complexity limits on another branch. This PR brings those changes over.

refactor: move fastapi routes out of function

---

src/griptape_nodes/exe_types/node_types.py

Fixes #1736 , but I am worried this might break other things. Let's battle test.

dicts are iterable, but they just result in keys, not what we actually want.

---

libraries/griptape_nodes_library/griptape_nodes_library/execution/for_each_end.py

Now only does it if exec out is disconnected.

Fixed issue where exec out connection was overridden every time workflow loaded.

---

libraries/griptape_nodes_library/griptape_nodes_library/workflows/end_flow.py
libraries/griptape_nodes_library/griptape_nodes_library/workflows/start_flow.py

* Remove default parameter lists on workflow nodes
* Add dynamic param metadata

Remove default parameter lists on workflow nodes. Add dynamic param metadata

---

src/griptape_nodes/retained_mode/managers/config_manager.py

* Prevent storing duplicates of the same file to workflows_to_register

Prevent storing duplicates of the same file to workflows_to_register

---

libraries/griptape_nodes_library/griptape_nodes_library/image/image_bash.py

Fixed disconnecting breaking issue in image bash functionality.
fixes: https://github.com/griptape-ai/griptape-nodes/issues/1766

Fix image bash disconnect crash

---

src/griptape_nodes/__init__.py
src/griptape_nodes/app/watch.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/updater/__init__.py
src/griptape_nodes/utils/uv_utils.py
tests/unit/utils/test_uv_utils.py

We were inconsistent about where we looked for uv. Some places relied on uv being in the path.
(hopefully) Closes #1769

fix: better detection of uv

---

src/griptape_nodes/__init__.py

- Add prompt asking users if they want to configure a bucket
- Explain bucket usage for multi-machine workflow and asset syncing
- Remove dependency on GTC storage backend selection
- Users can now configure buckets for cross-device syncing even with local storage

feat: present bucket configuration regardless of storage backend

---

src/griptape_nodes/retained_mode/events/workflow_events.py

fix: don't mark workflow as altered when running from registry

---

libraries/griptape_nodes_library/griptape_nodes_library/json/display_json.py

previously the display_json node couldn't handle yaml - now it does.
fixes: #1835

feature: display_json can handle yaml

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/image/display_image_grid.py
libraries/griptape_nodes_library/griptape_nodes_library/text/display_text_as_markdown.py
libraries/griptape_nodes_library/griptape_nodes_library/text/load_text.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/image_utils.py

Adds a new display image grid node, a display text as markdown node, updated the load text node to have a file picker, and gave it the ability to load pdf

feature: display image grid and improved text loader

---

libraries/griptape_nodes_library/workflows/templates/photography_team.py

The old workflow used ruleset lists which are no longer required

fixed photography team template workflow

---

libraries/griptape_nodes_library/griptape_nodes_library/lists/display_list.py

https://github.com/griptape-ai/griptape-vsl-gui/pull/1149
Goes with this PR above. With this update, it shows the images in the parameter list.

Update for images displaying in lists

---

libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/artifact_path_tethering.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/video_utils.py
libraries/griptape_nodes_library/griptape_nodes_library/video/load_video.py

Extrapolate parameter tethering from Load Image and apply it to Load Video

---

libraries/griptape_nodes_library/griptape_nodes_library/audio/load_audio.py
libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/artifact_path_tethering.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/video_utils.py
libraries/griptape_nodes_library/griptape_nodes_library/video/load_video.py

Load Audio now has tethered parameters (click in editor or feed it a URL or file path) treatment + universalized the URL extraction.

---

src/griptape_nodes/retained_mode/managers/static_files_manager.py

fix: increase timeout on static files upload

---

libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/griptape_cloud_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/openai_prompt.py
libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py
libraries/griptape_nodes_library/griptape_nodes_library/number/askulator.py
libraries/griptape_nodes_library/griptape_nodes_library/text/date_and_time.py
libraries/griptape_nodes_library/griptape_nodes_library/text/evaluate_text_result.py
libraries/griptape_nodes_library/griptape_nodes_library/text/scrape_web.py
libraries/griptape_nodes_library/griptape_nodes_library/text/search_web.py
libraries/griptape_nodes_library/griptape_nodes_library/text/summarize_text_task.py

* Add gpt-5 to default library configs

Add gpt-5 to default library configs

---

libraries/griptape_nodes_library/griptape_nodes_library/execution/base_iterative_nodes.py
libraries/griptape_nodes_library/griptape_nodes_library/lists/display_list.py

- Will update display list during iterations
- Deletes unnecessary parameters at the end if they exist (to prevent parameters from being deleted and recreated, which breaks connections) 
closes #1811

Updates display list as the For loop is iterating

---

libraries/griptape_nodes_library/griptape_nodes_library/audio/load_audio.py
libraries/griptape_nodes_library/griptape_nodes_library/image/load_image.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/artifact_path_tethering.py
libraries/griptape_nodes_library/griptape_nodes_library/video/load_video.py

Load* Nodes now have a single input of str OR artifact. Multiplex outputs of image and path.

---

src/griptape_nodes/bootstrap/workflow_executors/local_workflow_executor.py

closes #1802 
We were seeing some really weird generator behavior without the event queue. (reusing of generators) 
Seems like it's not a problem, but something we should continue to look into. 
follow up with #1905

Add Event Queue to Local Executor

---

libraries/griptape_nodes_library/griptape_nodes_library/lists/get_from_list.py

Make the GetFromList node compatible with any node that expects an explicit input type.

---

libraries/griptape_nodes_library/griptape_nodes_library/image/crop_image.py
libraries/griptape_nodes_library/griptape_nodes_library/image/extend_canvas.py
libraries/griptape_nodes_library/griptape_nodes_library/utils/image_utils.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/1914

Use NAMED_COLORS in base library

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library.json

We are going to `0.50.0`, right?

Update node library versions to match latest.

---

src/griptape_nodes/retained_mode/managers/flow_manager.py

Fix wonky control flow execution

---

.codecov.yml
.github/workflows/unit-tests.yml
Makefile
pyproject.toml
uv.lock

We need to improve our test coverage. Agents operate better with unit tests to check regressions against.

test: add codecov

---

src/griptape_nodes/retained_mode/managers/flow_manager.py

Propagate None and empty values through connections

---

libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/nim_prompt.py
src/griptape_nodes/retained_mode/managers/settings.py

This is a quick push for some NIM prompt models.

quick addition of NIM prompt models

---

docs/nodes/video/extract_audio.md
libraries/griptape_nodes_library/griptape_nodes_library.json
libraries/griptape_nodes_library/griptape_nodes_library/video/extract_audio.py
mkdocs.yml

----
📚 Documentation preview 📚: https://griptape-nodes--1980.org.readthedocs.build/en/1980/

Add ExtractAudio node to extract audio from video files with configurable format and quality settings, and update documentation accordingly.

---

libraries/griptape_nodes_library/griptape_nodes_library/utils/artifact_path_tethering.py

Ensure all parameters for Load* nodes sync whether file is selected by input connection, browser picker, or file picker.

---

src/griptape_nodes/__init__.py
src/griptape_nodes/app/app.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_fsm.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_provenance/base.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_provenance/github.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_provenance/local_file.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_provenance/package.py
src/griptape_nodes/retained_mode/managers/library_lifecycle/library_provenance/sandbox.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/utils/async_utils.py
tests/workflows/test_workflows.py

This makes it so that the UI can actually see the engine while its installing dependencies. Will create follow-up tasks to more gracefully handle this.

refactor: process all events concurrently and load libraries async

---

libraries/griptape_nodes_library/griptape_nodes_library/utils/artifact_path_tethering.py

refactor: use existing url validation for artifacvt tethering

---

libraries/griptape_nodes_library/griptape_nodes_library/image/paint_mask.py

This fixes the paint mask button

fix: paint mask now allows for painting

---

src/griptape_nodes/retained_mode/managers/node_manager.py

Was not registered..._until today!_

The Send Node Message request now has a handler registered.

---

src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/agent_manager.py
src/griptape_nodes/retained_mode/managers/arbitrary_code_exec_manager.py
src/griptape_nodes/retained_mode/managers/context_manager.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/object_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/managers/secrets_manager.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py
src/griptape_nodes/retained_mode/managers/sync_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py
tests/unit/retained_mode/managers/test_workflow_manager.py

All result details are added to the result objects. Prevents double logging and makes the results accessible to the editor.

---

libraries/griptape_nodes_library/griptape_nodes_library/engine/engine_node.py

1. Adds a `was_successful` bool for people who don't want to use the Control ports
2. Adds a text box up top containing the results so you don't have to go dig around at the bottom.

Enhance the Engine Node for easier view on details (success/failure event details)

---

src/griptape_nodes/exe_types/node_types.py

pssst, you can turn a DataNode into a Control Node now. DataNodes have hidden control ports that can be made visible.

---

src/griptape_nodes/bootstrap/workflow_executors/local_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_executors/workflow_executor.py
src/griptape_nodes/retained_mode/managers/agent_manager.py
src/griptape_nodes/retained_mode/managers/static_files_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py
tests/workflows/test_workflows.py

Future work can include broadcasting a app shutdown event on `__aexit__`

feat: add async context manager to local workflow executor

---

src/griptape_nodes/traits/options.py

Dynamic options lists can now survive a save/load.

---

src/griptape_nodes/retained_mode/managers/model_manager.py

Context: https://github.com/griptape-ai/griptape-vsl-gui/pull/1280#discussion_r2349586686
This is confusing behavior, remove for now.

refactor: remove download auto cleanup

---

src/griptape_nodes/cli/commands/models.py
src/griptape_nodes/retained_mode/managers/model_manager.py
src/griptape_nodes/utils/async_utils.py

Once a model download has started, users cannot cancel it because the model download runs in a thread. Threads cannot be stopped once they've started.
Run the model download in a separate process through the CLI interface `gtn models download <model id>`. This is easily cancelable.

feat: support proper model download cancellation

---

libraries/griptape_nodes_library/griptape_nodes_library/workflows/end_flow.py
src/griptape_nodes/exe_types/node_types.py
src/griptape_nodes/exe_types/param_components/__init__.py
src/griptape_nodes/exe_types/param_components/execution_status_component.py

Fixes #2209 
@zachgiordano I want to confirm this doesn't break any of the executor type nodes we have. Let me know and I will amend changes.

Created the execution_status component and applied to the EndNode

---

src/griptape_nodes/retained_mode/events/base_events.py
src/griptape_nodes/retained_mode/griptape_nodes.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/library_manager.py
src/griptape_nodes/retained_mode/managers/node_manager.py
src/griptape_nodes/retained_mode/managers/object_manager.py
src/griptape_nodes/retained_mode/managers/os_manager.py
src/griptape_nodes/retained_mode/managers/sync_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

refactor: accept native log level in result details

---

src/griptape_nodes/cli/main.py

feat: add --version flag to top level gtn command

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/torch_utils.py

Previous code checked for none in the L59 loop but not here

Fully check for empty pipe components

---

src/griptape_nodes/retained_mode/managers/flow_manager.py

Now properly cancels on a node failure.

Add Cancellation Logic into Single Node Resolution

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

Don't want to swing at actual filenames yet

Rename diffusions nodes

---

libraries/griptape_nodes_library/griptape_nodes_library/video/split_video.py

fix: split video clear on run

---

src/griptape_nodes/retained_mode/events/workflow_events.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Closes #2353 
Introduced with #2324

Fixes rename regression with file path. Fixes templates, too.

---

libraries/griptape_nodes_library/griptape_nodes_library/text/merge_texts.py
libraries/griptape_nodes_library/griptape_nodes_library/video/split_video.py

update: merge_text handles additional input types

---

src/griptape_nodes/bootstrap/workflow_executors/local_session_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_executors/local_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_executors/subprocess_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_executors/utils/__init__.py
src/griptape_nodes/bootstrap/workflow_executors/utils/subprocess_script.py

* Created new workflow executors:
* `LocalSessionWorkflowExecutor`
*  A subclass of the `LocalWorkflowExecutor` which emits ExecutionEvents to the API using a provided `session_id`
* `SubprocessWorkflowExecutor`
* Workflow executor class that uses the `LocalSessionWorkflowExecutor` to execute a workflow file in a subprocess, and listens to the Events from that workflow execution via the API using a session
Could potentially use more cleanup, but seems to be working for now. Might have to update this as we integrate.
Test script to utilize the SubprocessWorkflowExecutor
```python
import asyncio
import logging
from pathlib import Path
from griptape_nodes.bootstrap.workflow_executors.subprocess_workflow_executor import SubprocessWorkflowExecutor
from griptape_nodes.drivers.storage import …
```

Subprocess workflow executor with session events IPC

---

src/griptape_nodes/bootstrap/utils/__init__.py
src/griptape_nodes/bootstrap/utils/python_subprocess_executor.py
src/griptape_nodes/bootstrap/workflow_executors/subprocess_workflow_executor.py
src/griptape_nodes/bootstrap/workflow_publishers/__init__.py
src/griptape_nodes/bootstrap/workflow_publishers/local_workflow_publisher.py
src/griptape_nodes/bootstrap/workflow_publishers/subprocess_workflow_publisher.py
src/griptape_nodes/bootstrap/workflow_publishers/utils/__init__.py
src/griptape_nodes/bootstrap/workflow_publishers/utils/subprocess_script.py

* Add subprocess publisher
Test script:
```python
import asyncio
import logging
from pathlib import Path
from griptape_nodes.bootstrap.workflow_publishers.subprocess_workflow_publisher import SubprocessWorkflowPublisher
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
async def _main() -> None:
workflow_path = str(Path(__file__).parent / "GriptapeNodes" / "simple_agent.py")
subprocess_publisher = SubprocessWorkflowPublisher()
async with subprocess_publisher as publisher:
await publisher.arun(
workflow_name="simple_agent",
workflow_path=workflow_path,
publisher_name="AWS Deadline Cloud Library",
published_workflow_file_name="published_simple_agent",
)
logger.info(f"Published workflow to file: published_simple_agent.py")
if __name__ == "__main__": …
```

Add subprocess publisher

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/diffusion_pipeline_type_parameters.py

fix: maintain pipeline position when regenerating parameters

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/diffusion_pipeline_type_parameters.py

Fixes regression introduced in 112536a32368

fix: properly position "loras" parameter

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

Fixed malformed Python generation when input list of a runnable workflow was empty.

---

libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json

deps: bump peft to >=0.17.0

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_runtime_node.py

The HF model download message is a ParameterMessage, not a Parameter... Thankfully, both are elements

reorder runtime elements opposed to parameters

---

src/griptape_nodes/retained_mode/managers/workflow_manager.py

Fixes #2516 
The logic was intertwined and difficult enough to follow. Codify the scenarios (new file, saving existing file to a new one, overwriting existing one, and saving from a template).

Codify workflow saving scenarios to address regression.

---

libraries/griptape_nodes_library/griptape_nodes_library/text/merge_texts.py

MergeText node no longer throws away inputs of integer 0, float 0.0, boolean False, and other "falsey" values

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/nodes/diffusion_pipeline_builder_node.py
libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/huggingface_utils.py
src/griptape_nodes/exe_types/node_types.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/2514

BaseNode.state as property that can be marked volatile

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/diffusion/runtime_parameters.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/2527

Add seconds per iteration for base diffusion pipeline

---

src/griptape_nodes/node_library/workflow_registry.py
src/griptape_nodes/retained_mode/events/flow_events.py
src/griptape_nodes/retained_mode/managers/flow_manager.py
src/griptape_nodes/retained_mode/managers/workflow_manager.py

Adds a list of nodes used by a workflow in the workflow metadata

---

libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_model_parameter.py

Closes https://github.com/griptape-ai/griptape-nodes/issues/2544

When HF model choices change, use prior value if possible

---

libraries/griptape_nodes_library/griptape_nodes_library/tasks/mcp_task.py

[This PR](https://github.com/griptape-ai/griptape-nodes/pull/2567#discussion_r2412025215) highlighted a potential issue for the MCP task. Jason, I am not setup to test this, can you confirm it works?

Keep selected MCP server on reload if possible

---

libraries/griptape_nodes_library/griptape_nodes_library/config/prompt/nim_prompt.py

added new vision models to the NIM driver:
* meta/llama-4-maverick-17b-128e-instruct
* meta/llama-4-scout-17b-16e-instruct
* meta/llama-3.2-11b-vision-instruct
* meta/llama-3.2-90b-vision-instruct
fixes: #2550

update: added new vision models to NIM driver
